// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type AddMultistreamTargetRequest struct {
	// ID of the parent stream
	ID               string                      `pathParam:"style=simple,explode=false,name=id"`
	TargetAddPayload components.TargetAddPayload `request:"mediaType=application/json"`
}

func (a *AddMultistreamTargetRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AddMultistreamTargetRequest) GetTargetAddPayload() components.TargetAddPayload {
	if a == nil {
		return components.TargetAddPayload{}
	}
	return a.TargetAddPayload
}

type AddMultistreamTargetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (a *AddMultistreamTargetResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddMultistreamTargetResponse) GetError() *components.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
