// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type CreateClipTask struct {
	ID *string `json:"id,omitempty"`
}

func (o *CreateClipTask) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

// CreateClipData - Success
type CreateClipData struct {
	Asset components.Asset `json:"asset"`
	Task  CreateClipTask   `json:"task"`
}

func (o *CreateClipData) GetAsset() components.Asset {
	if o == nil {
		return components.Asset{}
	}
	return o.Asset
}

func (o *CreateClipData) GetTask() CreateClipTask {
	if o == nil {
		return CreateClipTask{}
	}
	return o.Task
}

type CreateClipResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Data *CreateClipData
	// Error
	Error *sdkerrors.Error
}

func (o *CreateClipResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateClipResponse) GetData() *CreateClipData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *CreateClipResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
