// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type CreateMultistreamTargetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	MultistreamTarget *components.MultistreamTarget
	// Error
	Error *components.Error
}

func (c *CreateMultistreamTargetResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateMultistreamTargetResponse) GetMultistreamTarget() *components.MultistreamTarget {
	if c == nil {
		return nil
	}
	return c.MultistreamTarget
}

func (c *CreateMultistreamTargetResponse) GetError() *components.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
