// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type CreateWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Webhook *components.Webhook
	// Error
	Error *components.Error
}

func (o *CreateWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateWebhookResponse) GetWebhook() *components.Webhook {
	if o == nil {
		return nil
	}
	return o.Webhook
}

func (o *CreateWebhookResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
