// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type CreateStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Stream *components.Stream
	// Error
	Error *components.Error
}

func (c *CreateStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateStreamResponse) GetStream() *components.Stream {
	if c == nil {
		return nil
	}
	return c.Stream
}

func (c *CreateStreamResponse) GetError() *components.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
