// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type CreateMultistreamTargetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	MultistreamTarget *components.MultistreamTarget
	// Error
	Error *sdkerrors.Error
}

func (o *CreateMultistreamTargetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateMultistreamTargetResponse) GetMultistreamTarget() *components.MultistreamTarget {
	if o == nil {
		return nil
	}
	return o.MultistreamTarget
}

func (o *CreateMultistreamTargetResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
