// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type CreateSigningKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	SigningKey *components.SigningKey
	// Error
	Error *components.Error
}

func (c *CreateSigningKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSigningKeyResponse) GetSigningKey() *components.SigningKey {
	if c == nil {
		return nil
	}
	return c.SigningKey
}

func (c *CreateSigningKeyResponse) GetError() *components.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
