// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type DeleteRoomRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteRoomRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteRoomResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (o *DeleteRoomResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteRoomResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
