// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type DeleteStreamRequest struct {
	// ID of the stream
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteStreamRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d *DeleteStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteStreamResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
