// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type DeleteRoomUserRequest struct {
	ID     string `pathParam:"style=simple,explode=false,name=id"`
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

func (d *DeleteRoomUserRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteRoomUserRequest) GetUserID() string {
	if d == nil {
		return ""
	}
	return d.UserID
}

type DeleteRoomUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (d *DeleteRoomUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteRoomUserResponse) GetError() *components.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
