// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GenAudioToTextResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TextResponse *components.TextResponse
	// Error
	StudioAPIError *components.StudioAPIError
}

func (g *GenAudioToTextResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GenAudioToTextResponse) GetTextResponse() *components.TextResponse {
	if g == nil {
		return nil
	}
	return g.TextResponse
}

func (g *GenAudioToTextResponse) GetStudioAPIError() *components.StudioAPIError {
	if g == nil {
		return nil
	}
	return g.StudioAPIError
}
