// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GenImageToImageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ImageResponse *components.ImageResponse
	// Error
	StudioAPIError *components.StudioAPIError
}

func (g *GenImageToImageResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GenImageToImageResponse) GetImageResponse() *components.ImageResponse {
	if g == nil {
		return nil
	}
	return g.ImageResponse
}

func (g *GenImageToImageResponse) GetStudioAPIError() *components.StudioAPIError {
	if g == nil {
		return nil
	}
	return g.StudioAPIError
}
