// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/livepeer/livepeer-go/internal/utils"
	"github.com/livepeer/livepeer-go/models/components"
	"time"
)

type QueryParamFromType string

const (
	QueryParamFromTypeDateTime QueryParamFromType = "date-time"
	QueryParamFromTypeInteger  QueryParamFromType = "integer"
)

// QueryParamFrom - Start timestamp for the query range (inclusive)
type QueryParamFrom struct {
	DateTime *time.Time `queryParam:"inline,name=from"`
	Integer  *int64     `queryParam:"inline,name=from"`

	Type QueryParamFromType
}

func CreateQueryParamFromDateTime(dateTime time.Time) QueryParamFrom {
	typ := QueryParamFromTypeDateTime

	return QueryParamFrom{
		DateTime: &dateTime,
		Type:     typ,
	}
}

func CreateQueryParamFromInteger(integer int64) QueryParamFrom {
	typ := QueryParamFromTypeInteger

	return QueryParamFrom{
		Integer: &integer,
		Type:    typ,
	}
}

func (u *QueryParamFrom) UnmarshalJSON(data []byte) error {

	var dateTime time.Time = time.Time{}
	if err := utils.UnmarshalJSON(data, &dateTime, "", true, nil); err == nil {
		u.DateTime = &dateTime
		u.Type = QueryParamFromTypeDateTime
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = QueryParamFromTypeInteger
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for QueryParamFrom", string(data))
}

func (u QueryParamFrom) MarshalJSON() ([]byte, error) {
	if u.DateTime != nil {
		return utils.MarshalJSON(u.DateTime, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	return nil, errors.New("could not marshal union type QueryParamFrom: all fields are null")
}

type QueryParamToType string

const (
	QueryParamToTypeDateTime QueryParamToType = "date-time"
	QueryParamToTypeInteger  QueryParamToType = "integer"
)

// QueryParamTo - End timestamp for the query range (exclusive)
type QueryParamTo struct {
	DateTime *time.Time `queryParam:"inline,name=to"`
	Integer  *int64     `queryParam:"inline,name=to"`

	Type QueryParamToType
}

func CreateQueryParamToDateTime(dateTime time.Time) QueryParamTo {
	typ := QueryParamToTypeDateTime

	return QueryParamTo{
		DateTime: &dateTime,
		Type:     typ,
	}
}

func CreateQueryParamToInteger(integer int64) QueryParamTo {
	typ := QueryParamToTypeInteger

	return QueryParamTo{
		Integer: &integer,
		Type:    typ,
	}
}

func (u *QueryParamTo) UnmarshalJSON(data []byte) error {

	var dateTime time.Time = time.Time{}
	if err := utils.UnmarshalJSON(data, &dateTime, "", true, nil); err == nil {
		u.DateTime = &dateTime
		u.Type = QueryParamToTypeDateTime
		return nil
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		u.Integer = &integer
		u.Type = QueryParamToTypeInteger
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for QueryParamTo", string(data))
}

func (u QueryParamTo) MarshalJSON() ([]byte, error) {
	if u.DateTime != nil {
		return utils.MarshalJSON(u.DateTime, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	return nil, errors.New("could not marshal union type QueryParamTo: all fields are null")
}

// QueryParamTimeStep - The time step to aggregate viewership metrics by
type QueryParamTimeStep string

const (
	QueryParamTimeStepHour  QueryParamTimeStep = "hour"
	QueryParamTimeStepDay   QueryParamTimeStep = "day"
	QueryParamTimeStepWeek  QueryParamTimeStep = "week"
	QueryParamTimeStepMonth QueryParamTimeStep = "month"
	QueryParamTimeStepYear  QueryParamTimeStep = "year"
)

func (e QueryParamTimeStep) ToPointer() *QueryParamTimeStep {
	return &e
}
func (e *QueryParamTimeStep) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "hour":
		fallthrough
	case "day":
		fallthrough
	case "week":
		fallthrough
	case "month":
		fallthrough
	case "year":
		*e = QueryParamTimeStep(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamTimeStep: %v", v)
	}
}

type GetCreatorViewershipMetricsQueryParamBreakdownBy string

const (
	GetCreatorViewershipMetricsQueryParamBreakdownByDeviceType    GetCreatorViewershipMetricsQueryParamBreakdownBy = "deviceType"
	GetCreatorViewershipMetricsQueryParamBreakdownByDevice        GetCreatorViewershipMetricsQueryParamBreakdownBy = "device"
	GetCreatorViewershipMetricsQueryParamBreakdownByCPU           GetCreatorViewershipMetricsQueryParamBreakdownBy = "cpu"
	GetCreatorViewershipMetricsQueryParamBreakdownByOs            GetCreatorViewershipMetricsQueryParamBreakdownBy = "os"
	GetCreatorViewershipMetricsQueryParamBreakdownByBrowser       GetCreatorViewershipMetricsQueryParamBreakdownBy = "browser"
	GetCreatorViewershipMetricsQueryParamBreakdownByBrowserEngine GetCreatorViewershipMetricsQueryParamBreakdownBy = "browserEngine"
	GetCreatorViewershipMetricsQueryParamBreakdownByContinent     GetCreatorViewershipMetricsQueryParamBreakdownBy = "continent"
	GetCreatorViewershipMetricsQueryParamBreakdownByCountry       GetCreatorViewershipMetricsQueryParamBreakdownBy = "country"
	GetCreatorViewershipMetricsQueryParamBreakdownBySubdivision   GetCreatorViewershipMetricsQueryParamBreakdownBy = "subdivision"
	GetCreatorViewershipMetricsQueryParamBreakdownByTimezone      GetCreatorViewershipMetricsQueryParamBreakdownBy = "timezone"
	GetCreatorViewershipMetricsQueryParamBreakdownByViewerID      GetCreatorViewershipMetricsQueryParamBreakdownBy = "viewerId"
)

func (e GetCreatorViewershipMetricsQueryParamBreakdownBy) ToPointer() *GetCreatorViewershipMetricsQueryParamBreakdownBy {
	return &e
}
func (e *GetCreatorViewershipMetricsQueryParamBreakdownBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "deviceType":
		fallthrough
	case "device":
		fallthrough
	case "cpu":
		fallthrough
	case "os":
		fallthrough
	case "browser":
		fallthrough
	case "browserEngine":
		fallthrough
	case "continent":
		fallthrough
	case "country":
		fallthrough
	case "subdivision":
		fallthrough
	case "timezone":
		fallthrough
	case "viewerId":
		*e = GetCreatorViewershipMetricsQueryParamBreakdownBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCreatorViewershipMetricsQueryParamBreakdownBy: %v", v)
	}
}

type GetCreatorViewershipMetricsRequest struct {
	// Start timestamp for the query range (inclusive)
	From *QueryParamFrom `queryParam:"style=form,explode=true,name=from"`
	// End timestamp for the query range (exclusive)
	To *QueryParamTo `queryParam:"style=form,explode=true,name=to"`
	// The time step to aggregate viewership metrics by
	TimeStep *QueryParamTimeStep `queryParam:"style=form,explode=true,name=timeStep"`
	// The asset ID to filter metrics for
	AssetID *string `queryParam:"style=form,explode=true,name=assetId"`
	// The stream ID to filter metrics for
	StreamID *string `queryParam:"style=form,explode=true,name=streamId"`
	// The creator ID to filter the query results
	CreatorID *string `queryParam:"style=form,explode=true,name=creatorId"`
	// The list of fields to break down the query results. Specify this
	// query-string multiple times to break down by multiple fields.
	//
	BreakdownBy []GetCreatorViewershipMetricsQueryParamBreakdownBy `queryParam:"style=form,explode=true,name=breakdownBy[]"`
}

func (g *GetCreatorViewershipMetricsRequest) GetFrom() *QueryParamFrom {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetCreatorViewershipMetricsRequest) GetTo() *QueryParamTo {
	if g == nil {
		return nil
	}
	return g.To
}

func (g *GetCreatorViewershipMetricsRequest) GetTimeStep() *QueryParamTimeStep {
	if g == nil {
		return nil
	}
	return g.TimeStep
}

func (g *GetCreatorViewershipMetricsRequest) GetAssetID() *string {
	if g == nil {
		return nil
	}
	return g.AssetID
}

func (g *GetCreatorViewershipMetricsRequest) GetStreamID() *string {
	if g == nil {
		return nil
	}
	return g.StreamID
}

func (g *GetCreatorViewershipMetricsRequest) GetCreatorID() *string {
	if g == nil {
		return nil
	}
	return g.CreatorID
}

func (g *GetCreatorViewershipMetricsRequest) GetBreakdownBy() []GetCreatorViewershipMetricsQueryParamBreakdownBy {
	if g == nil {
		return nil
	}
	return g.BreakdownBy
}

type GetCreatorViewershipMetricsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A list of Metric objects
	Data []components.ViewershipMetric
	// Error
	Error *components.Error
}

func (g *GetCreatorViewershipMetricsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCreatorViewershipMetricsResponse) GetData() []components.ViewershipMetric {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetCreatorViewershipMetricsResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
