// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

// GetDataUsageQueryQueryParamTimeStep - The time step to aggregate viewership metrics by
type GetDataUsageQueryQueryParamTimeStep string

const (
	GetDataUsageQueryQueryParamTimeStepHour GetDataUsageQueryQueryParamTimeStep = "hour"
	GetDataUsageQueryQueryParamTimeStepDay  GetDataUsageQueryQueryParamTimeStep = "day"
)

func (e GetDataUsageQueryQueryParamTimeStep) ToPointer() *GetDataUsageQueryQueryParamTimeStep {
	return &e
}

func (e *GetDataUsageQueryQueryParamTimeStep) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "hour":
		fallthrough
	case "day":
		*e = GetDataUsageQueryQueryParamTimeStep(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetDataUsageQueryQueryParamTimeStep: %v", v)
	}
}

type GetDataUsageQueryRequest struct {
	// Start millis timestamp for the query range (inclusive)
	//
	From *int64 `queryParam:"style=form,explode=true,name=from"`
	// End millis timestamp for the query range (exclusive)
	//
	To *int64 `queryParam:"style=form,explode=true,name=to"`
	// The time step to aggregate viewership metrics by
	//
	TimeStep *GetDataUsageQueryQueryParamTimeStep `queryParam:"style=form,explode=true,name=timeStep"`
	// The creator ID to filter the query results
	//
	CreatorID *string `queryParam:"style=form,explode=true,name=creatorId"`
}

func (o *GetDataUsageQueryRequest) GetFrom() *int64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *GetDataUsageQueryRequest) GetTo() *int64 {
	if o == nil {
		return nil
	}
	return o.To
}

func (o *GetDataUsageQueryRequest) GetTimeStep() *GetDataUsageQueryQueryParamTimeStep {
	if o == nil {
		return nil
	}
	return o.TimeStep
}

func (o *GetDataUsageQueryRequest) GetCreatorID() *string {
	if o == nil {
		return nil
	}
	return o.CreatorID
}

type GetDataUsageQueryResponse struct {
	HTTPMeta components.HTTPMetadata
	// A Usage Metric object
	UsageMetric *components.UsageMetric
	// Error
	Error *sdkerrors.Error
}

func (o *GetDataUsageQueryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDataUsageQueryResponse) GetUsageMetric() *components.UsageMetric {
	if o == nil {
		return nil
	}
	return o.UsageMetric
}

func (o *GetDataUsageQueryResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
