// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type GetMultistreamTargetRequest struct {
	// ID of the multistream target
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetMultistreamTargetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetMultistreamTargetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	MultistreamTarget *components.MultistreamTarget
	// Error
	Error *sdkerrors.Error
}

func (o *GetMultistreamTargetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetMultistreamTargetResponse) GetMultistreamTarget() *components.MultistreamTarget {
	if o == nil {
		return nil
	}
	return o.MultistreamTarget
}

func (o *GetMultistreamTargetResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
