// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GetMultistreamTargetRequest struct {
	// ID of the multistream target
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetMultistreamTargetRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetMultistreamTargetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	MultistreamTarget *components.MultistreamTarget
	// Error
	Error *components.Error
}

func (g *GetMultistreamTargetResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMultistreamTargetResponse) GetMultistreamTarget() *components.MultistreamTarget {
	if g == nil {
		return nil
	}
	return g.MultistreamTarget
}

func (g *GetMultistreamTargetResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
