// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GetPublicViewershipMetricsRequest struct {
	// The playback ID to filter the query results. This can be a canonical
	// playback ID from Livepeer assets or streams, or dStorage identifiers
	// for assets
	//
	PlaybackID string `pathParam:"style=simple,explode=false,name=playbackId"`
}

func (g *GetPublicViewershipMetricsRequest) GetPlaybackID() string {
	if g == nil {
		return ""
	}
	return g.PlaybackID
}

// GetPublicViewershipMetricsData - A simplified metric object about aggregate viewership of an
// asset. Either playbackId or dStorageUrl will be set.
type GetPublicViewershipMetricsData struct {
	// The playback ID associated with the metric.
	PlaybackID *string `json:"playbackId,omitempty"`
	// The URL of the distributed storage used for the asset
	DStorageURL *string `json:"dStorageUrl,omitempty"`
	// The number of views for the stream/asset.
	ViewCount *int64 `json:"viewCount,omitempty"`
	// The total playtime in minutes for the stream/asset.
	PlaytimeMins *float64 `json:"playtimeMins,omitempty"`
}

func (g *GetPublicViewershipMetricsData) GetPlaybackID() *string {
	if g == nil {
		return nil
	}
	return g.PlaybackID
}

func (g *GetPublicViewershipMetricsData) GetDStorageURL() *string {
	if g == nil {
		return nil
	}
	return g.DStorageURL
}

func (g *GetPublicViewershipMetricsData) GetViewCount() *int64 {
	if g == nil {
		return nil
	}
	return g.ViewCount
}

func (g *GetPublicViewershipMetricsData) GetPlaytimeMins() *float64 {
	if g == nil {
		return nil
	}
	return g.PlaytimeMins
}

type GetPublicViewershipMetricsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A single Metric object with the viewCount and playtimeMins metrics.
	Data *GetPublicViewershipMetricsData
	// Error
	Error *components.Error
}

func (g *GetPublicViewershipMetricsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPublicViewershipMetricsResponse) GetData() *GetPublicViewershipMetricsData {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetPublicViewershipMetricsResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
