// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"livepeer/models/components"
	"net/http"
)

type GetRoomUserDetailsRequest struct {
	// ID of the room
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// ID of the user
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

func (o *GetRoomUserDetailsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetRoomUserDetailsRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type GetRoomUserDetailsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	GetRoomUserResponse *components.GetRoomUserResponse
}

func (o *GetRoomUserDetailsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRoomUserDetailsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRoomUserDetailsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetRoomUserDetailsResponse) GetGetRoomUserResponse() *components.GetRoomUserResponse {
	if o == nil {
		return nil
	}
	return o.GetRoomUserResponse
}
