// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type GetRoomIDRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetRoomIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetRoomIDResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Room *components.Room
	// Error
	Error *sdkerrors.Error
}

func (o *GetRoomIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetRoomIDResponse) GetRoom() *components.Room {
	if o == nil {
		return nil
	}
	return o.Room
}

func (o *GetRoomIDResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
