// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GetRoomRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetRoomRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetRoomResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Room *components.Room
	// Error
	Error *components.Error
}

func (g *GetRoomResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRoomResponse) GetRoom() *components.Room {
	if g == nil {
		return nil
	}
	return g.Room
}

func (g *GetRoomResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
