// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GetSessionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Data []components.Session
	// Error
	Error *components.Error
}

func (g *GetSessionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSessionsResponse) GetData() []components.Session {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetSessionsResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
