// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type GetStreamIDRequest struct {
	// ID of the stream
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetStreamIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetStreamIDResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Stream *components.Stream
	// Error
	Error *sdkerrors.Error
}

func (o *GetStreamIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetStreamIDResponse) GetStream() *components.Stream {
	if o == nil {
		return nil
	}
	return o.Stream
}

func (o *GetStreamIDResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
