// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type GetStreamParentIDSessionsRequest struct {
	// ID of the parent stream
	ParentID string `pathParam:"style=simple,explode=false,name=parentId"`
	// Flag indicating if the response should only include recorded
	// sessions
	//
	Record *int64 `queryParam:"style=form,explode=true,name=record"`
}

func (o *GetStreamParentIDSessionsRequest) GetParentID() string {
	if o == nil {
		return ""
	}
	return o.ParentID
}

func (o *GetStreamParentIDSessionsRequest) GetRecord() *int64 {
	if o == nil {
		return nil
	}
	return o.Record
}

type GetStreamParentIDSessionsResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Sessions []components.Session
	// Error
	Error *sdkerrors.Error
}

func (o *GetStreamParentIDSessionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetStreamParentIDSessionsResponse) GetSessions() []components.Session {
	if o == nil {
		return nil
	}
	return o.Sessions
}

func (o *GetStreamParentIDSessionsResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
