// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GetSigningKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Data []components.SigningKey
	// Error
	Error *components.Error
}

func (g *GetSigningKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSigningKeysResponse) GetData() []components.SigningKey {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetSigningKeysResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
