// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GetTaskTaskIDRequest struct {
	// ID of the task
	TaskID string `pathParam:"style=simple,explode=false,name=taskId"`
}

func (o *GetTaskTaskIDRequest) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

type GetTaskTaskIDResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Task *components.Task
}

func (o *GetTaskTaskIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTaskTaskIDResponse) GetTask() *components.Task {
	if o == nil {
		return nil
	}
	return o.Task
}
