// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type GetTaskResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Tasks []components.Task
	// Error
	Error *sdkerrors.Error
}

func (o *GetTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTaskResponse) GetTasks() []components.Task {
	if o == nil {
		return nil
	}
	return o.Tasks
}

func (o *GetTaskResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
