// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type GetWebhookLogRequest struct {
	ID    string `pathParam:"style=simple,explode=false,name=id"`
	LogID string `pathParam:"style=simple,explode=false,name=logId"`
}

func (o *GetWebhookLogRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetWebhookLogRequest) GetLogID() string {
	if o == nil {
		return ""
	}
	return o.LogID
}

type GetWebhookLogResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	WebhookLog *components.WebhookLog
	// Error
	Error *sdkerrors.Error
}

func (o *GetWebhookLogResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWebhookLogResponse) GetWebhookLog() *components.WebhookLog {
	if o == nil {
		return nil
	}
	return o.WebhookLog
}

func (o *GetWebhookLogResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
