// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type GetWebhookRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetWebhookRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Webhook *components.Webhook
	// Error
	Error *components.Error
}

func (g *GetWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWebhookResponse) GetWebhook() *components.Webhook {
	if g == nil {
		return nil
	}
	return g.Webhook
}

func (g *GetWebhookResponse) GetError() *components.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
