// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type GetWebhooksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Data []components.Webhook
	// Error
	Error *sdkerrors.Error
}

func (o *GetWebhooksResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWebhooksResponse) GetData() []components.Webhook {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetWebhooksResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
