// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type GetWebhookLogsRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetWebhookLogsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetWebhookLogsResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Data []components.WebhookLog
	// Error
	Error *sdkerrors.Error
}

func (o *GetWebhookLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetWebhookLogsResponse) GetData() []components.WebhookLog {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetWebhookLogsResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
