// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type PostWebhookIDLogLogIDResendRequest struct {
	ID    string `pathParam:"style=simple,explode=false,name=id"`
	LogID string `pathParam:"style=simple,explode=false,name=logId"`
}

func (o *PostWebhookIDLogLogIDResendRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PostWebhookIDLogLogIDResendRequest) GetLogID() string {
	if o == nil {
		return ""
	}
	return o.LogID
}

type PostWebhookIDLogLogIDResendResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	WebhookLog *components.WebhookLog
	// Error
	Error *sdkerrors.Error
}

func (o *PostWebhookIDLogLogIDResendResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostWebhookIDLogLogIDResendResponse) GetWebhookLog() *components.WebhookLog {
	if o == nil {
		return nil
	}
	return o.WebhookLog
}

func (o *PostWebhookIDLogLogIDResendResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
