// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type Task struct {
	ID *string `json:"id,omitempty"`
}

func (o *Task) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

// PostAssetRequestUploadResponseBody - Success
type PostAssetRequestUploadResponseBody struct {
	// The direct upload endpoint for which supports PUT requests. **It is recommended to use the Tus endpoint for a better upload experience.**
	URL string `json:"url"`
	// The [Tus-compatible](https://tus.io/) endpoint for resumable uploads. **This is the recommended way to upload assets.** See the [Tus-js](https://github.com/tus/tus-js-client) client for more information.
	TusEndpoint string           `json:"tusEndpoint"`
	Asset       components.Asset `json:"asset"`
	Task        Task             `json:"task"`
}

func (o *PostAssetRequestUploadResponseBody) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *PostAssetRequestUploadResponseBody) GetTusEndpoint() string {
	if o == nil {
		return ""
	}
	return o.TusEndpoint
}

func (o *PostAssetRequestUploadResponseBody) GetAsset() components.Asset {
	if o == nil {
		return components.Asset{}
	}
	return o.Asset
}

func (o *PostAssetRequestUploadResponseBody) GetTask() Task {
	if o == nil {
		return Task{}
	}
	return o.Task
}

type PostAssetRequestUploadResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Object *PostAssetRequestUploadResponseBody
	// Error
	Error *sdkerrors.Error
}

func (o *PostAssetRequestUploadResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostAssetRequestUploadResponse) GetObject() *PostAssetRequestUploadResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *PostAssetRequestUploadResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
