// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type PostClipTask struct {
	ID *string `json:"id,omitempty"`
}

func (o *PostClipTask) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

// PostClipResponseBody - Success
type PostClipResponseBody struct {
	Asset components.Asset `json:"asset"`
	Task  PostClipTask     `json:"task"`
}

func (o *PostClipResponseBody) GetAsset() components.Asset {
	if o == nil {
		return components.Asset{}
	}
	return o.Asset
}

func (o *PostClipResponseBody) GetTask() PostClipTask {
	if o == nil {
		return PostClipTask{}
	}
	return o.Task
}

type PostClipResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Object *PostClipResponseBody
	// Error
	Error *sdkerrors.Error
}

func (o *PostClipResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostClipResponse) GetObject() *PostClipResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *PostClipResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
