// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type PostMultistreamTargetResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	MultistreamTargets []components.MultistreamTarget
	// Error
	Error *sdkerrors.Error
}

func (o *PostMultistreamTargetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostMultistreamTargetResponse) GetMultistreamTargets() []components.MultistreamTarget {
	if o == nil {
		return nil
	}
	return o.MultistreamTargets
}

func (o *PostMultistreamTargetResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
