// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type PostAccessControlSigningKeyResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	SigningKey *components.SigningKey
	// Error
	Error *sdkerrors.Error
}

func (o *PostAccessControlSigningKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostAccessControlSigningKeyResponse) GetSigningKey() *components.SigningKey {
	if o == nil {
		return nil
	}
	return o.SigningKey
}

func (o *PostAccessControlSigningKeyResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
