// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type PostRoomResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	CreateRoomResponse *components.CreateRoomResponse
	// Error
	Error *sdkerrors.Error
}

func (o *PostRoomResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostRoomResponse) GetCreateRoomResponse() *components.CreateRoomResponse {
	if o == nil {
		return nil
	}
	return o.CreateRoomResponse
}

func (o *PostRoomResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
