// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type ResendWebhookRequest struct {
	ID    string `pathParam:"style=simple,explode=false,name=id"`
	LogID string `pathParam:"style=simple,explode=false,name=logId"`
}

func (o *ResendWebhookRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ResendWebhookRequest) GetLogID() string {
	if o == nil {
		return ""
	}
	return o.LogID
}

type ResendWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	WebhookLog *components.WebhookLog
	// Error
	Error *components.Error
}

func (o *ResendWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ResendWebhookResponse) GetWebhookLog() *components.WebhookLog {
	if o == nil {
		return nil
	}
	return o.WebhookLog
}

func (o *ResendWebhookResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
