// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type StartRoomEgressRequest struct {
	ID                string                       `pathParam:"style=simple,explode=false,name=id"`
	RoomEgressPayload components.RoomEgressPayload `request:"mediaType=application/json"`
}

func (s *StartRoomEgressRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StartRoomEgressRequest) GetRoomEgressPayload() components.RoomEgressPayload {
	if s == nil {
		return components.RoomEgressPayload{}
	}
	return s.RoomEgressPayload
}

type StartRoomEgressResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (s *StartRoomEgressResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StartRoomEgressResponse) GetError() *components.Error {
	if s == nil {
		return nil
	}
	return s.Error
}
