// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type TerminateStreamRequest struct {
	// ID of the stream
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *TerminateStreamRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type TerminateStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *sdkerrors.Error
}

func (o *TerminateStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TerminateStreamResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
