// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type TranscodeVideoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Task *components.Task
	// Error
	Error *components.Error
}

func (o *TranscodeVideoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TranscodeVideoResponse) GetTask() *components.Task {
	if o == nil {
		return nil
	}
	return o.Task
}

func (o *TranscodeVideoResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
