// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type UpdateStreamRequest struct {
	// ID of the stream
	ID                 string                        `pathParam:"style=simple,explode=false,name=id"`
	StreamPatchPayload components.StreamPatchPayload `request:"mediaType=application/json"`
}

func (o *UpdateStreamRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateStreamRequest) GetStreamPatchPayload() components.StreamPatchPayload {
	if o == nil {
		return components.StreamPatchPayload{}
	}
	return o.StreamPatchPayload
}

type UpdateStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (o *UpdateStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateStreamResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
