// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
)

type UpdateMultistreamTargetRequest struct {
	// ID of the multistream target
	ID                string                            `pathParam:"style=simple,explode=false,name=id"`
	MultistreamTarget components.MultistreamTargetInput `request:"mediaType=application/json"`
}

func (u *UpdateMultistreamTargetRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateMultistreamTargetRequest) GetMultistreamTarget() components.MultistreamTargetInput {
	if u == nil {
		return components.MultistreamTargetInput{}
	}
	return u.MultistreamTarget
}

type UpdateMultistreamTargetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	Error *components.Error
}

func (u *UpdateMultistreamTargetResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateMultistreamTargetResponse) GetError() *components.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
