// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type UpdateSigningKeyRequestBody struct {
	Disabled *bool   `json:"disabled,omitempty"`
	Name     *string `json:"name,omitempty"`
}

func (o *UpdateSigningKeyRequestBody) GetDisabled() *bool {
	if o == nil {
		return nil
	}
	return o.Disabled
}

func (o *UpdateSigningKeyRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type UpdateSigningKeyRequest struct {
	// ID of the signing key
	KeyID       string                      `pathParam:"style=simple,explode=false,name=keyId"`
	RequestBody UpdateSigningKeyRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateSigningKeyRequest) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

func (o *UpdateSigningKeyRequest) GetRequestBody() UpdateSigningKeyRequestBody {
	if o == nil {
		return UpdateSigningKeyRequestBody{}
	}
	return o.RequestBody
}

type UpdateSigningKeyResponse struct {
	HTTPMeta components.HTTPMetadata
	// Error
	Error *sdkerrors.Error
}

func (o *UpdateSigningKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateSigningKeyResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
