// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type UpdateWebhookRequest struct {
	ID      string                  `pathParam:"style=simple,explode=false,name=id"`
	Webhook components.WebhookInput `request:"mediaType=application/json"`
}

func (o *UpdateWebhookRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateWebhookRequest) GetWebhook() components.WebhookInput {
	if o == nil {
		return components.WebhookInput{}
	}
	return o.Webhook
}

type UpdateWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Webhook *components.Webhook
	// Error
	Error *sdkerrors.Error
}

func (o *UpdateWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateWebhookResponse) GetWebhook() *components.Webhook {
	if o == nil {
		return nil
	}
	return o.Webhook
}

func (o *UpdateWebhookResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
