// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/livepeer/livepeer-go/models/components"
	"github.com/livepeer/livepeer-go/models/sdkerrors"
)

type UploadAssetTask struct {
	ID *string `json:"id,omitempty"`
}

func (o *UploadAssetTask) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

// UploadAssetData - Success
type UploadAssetData struct {
	Asset components.Asset `json:"asset"`
	Task  UploadAssetTask  `json:"task"`
}

func (o *UploadAssetData) GetAsset() components.Asset {
	if o == nil {
		return components.Asset{}
	}
	return o.Asset
}

func (o *UploadAssetData) GetTask() UploadAssetTask {
	if o == nil {
		return UploadAssetTask{}
	}
	return o.Task
}

type UploadAssetResponse struct {
	HTTPMeta components.HTTPMetadata
	// Success
	Data *UploadAssetData
	// Error
	Error *sdkerrors.Error
}

func (o *UploadAssetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UploadAssetResponse) GetData() *UploadAssetData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *UploadAssetResponse) GetError() *sdkerrors.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
