// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/livepeer/livepeer-go/internal/utils"
	"github.com/livepeer/livepeer-go/models/components"
)

type GenImageToVideoGenerateResponse500ResponseBodyType string

const (
	GenImageToVideoGenerateResponse500ResponseBodyTypeHTTPError      GenImageToVideoGenerateResponse500ResponseBodyType = "HTTPError"
	GenImageToVideoGenerateResponse500ResponseBodyTypeStudioAPIError GenImageToVideoGenerateResponse500ResponseBodyType = "studio-api-error"
)

// GenImageToVideoGenerateResponse500ResponseBody - Internal Server Error
type GenImageToVideoGenerateResponse500ResponseBody struct {
	HTTPError      *components.HTTPError      `queryParam:"inline,name=responseBody"`
	StudioAPIError *components.StudioAPIError `queryParam:"inline,name=responseBody"`

	Type GenImageToVideoGenerateResponse500ResponseBodyType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GenImageToVideoGenerateResponse500ResponseBody{}

func CreateGenImageToVideoGenerateResponse500ResponseBodyHTTPError(httpError components.HTTPError) GenImageToVideoGenerateResponse500ResponseBody {
	typ := GenImageToVideoGenerateResponse500ResponseBodyTypeHTTPError

	return GenImageToVideoGenerateResponse500ResponseBody{
		HTTPError: &httpError,
		Type:      typ,
	}
}

func CreateGenImageToVideoGenerateResponse500ResponseBodyStudioAPIError(studioAPIError components.StudioAPIError) GenImageToVideoGenerateResponse500ResponseBody {
	typ := GenImageToVideoGenerateResponse500ResponseBodyTypeStudioAPIError

	return GenImageToVideoGenerateResponse500ResponseBody{
		StudioAPIError: &studioAPIError,
		Type:           typ,
	}
}

func (u *GenImageToVideoGenerateResponse500ResponseBody) UnmarshalJSON(data []byte) error {

	var httpError components.HTTPError = components.HTTPError{}
	if err := utils.UnmarshalJSON(data, &httpError, "", true, nil); err == nil {
		u.HTTPError = &httpError
		u.Type = GenImageToVideoGenerateResponse500ResponseBodyTypeHTTPError
		return nil
	}

	var studioAPIError components.StudioAPIError = components.StudioAPIError{}
	if err := utils.UnmarshalJSON(data, &studioAPIError, "", true, nil); err == nil {
		u.StudioAPIError = &studioAPIError
		u.Type = GenImageToVideoGenerateResponse500ResponseBodyTypeStudioAPIError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GenImageToVideoGenerateResponse500ResponseBody", string(data))
}

func (u GenImageToVideoGenerateResponse500ResponseBody) MarshalJSON() ([]byte, error) {
	if u.HTTPError != nil {
		return utils.MarshalJSON(u.HTTPError, "", true)
	}

	if u.StudioAPIError != nil {
		return utils.MarshalJSON(u.StudioAPIError, "", true)
	}

	return nil, errors.New("could not marshal union type GenImageToVideoGenerateResponse500ResponseBody: all fields are null")
}

func (u GenImageToVideoGenerateResponse500ResponseBody) Error() string {
	switch u.Type {
	case GenImageToVideoGenerateResponse500ResponseBodyTypeHTTPError:
		data, _ := json.Marshal(u.HTTPError)
		return string(data)
	case GenImageToVideoGenerateResponse500ResponseBodyTypeStudioAPIError:
		data, _ := json.Marshal(u.StudioAPIError)
		return string(data)
	default:
		return "unknown error"
	}
}

type GenImageToVideoGenerateResponseResponseBodyType string

const (
	GenImageToVideoGenerateResponseResponseBodyTypeHTTPValidationError GenImageToVideoGenerateResponseResponseBodyType = "HTTPValidationError"
	GenImageToVideoGenerateResponseResponseBodyTypeStudioAPIError      GenImageToVideoGenerateResponseResponseBodyType = "studio-api-error"
)

// GenImageToVideoGenerateResponseResponseBody - Validation Error
type GenImageToVideoGenerateResponseResponseBody struct {
	HTTPValidationError *components.HTTPValidationError `queryParam:"inline,name=responseBody"`
	StudioAPIError      *components.StudioAPIError      `queryParam:"inline,name=responseBody"`

	Type GenImageToVideoGenerateResponseResponseBodyType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GenImageToVideoGenerateResponseResponseBody{}

func CreateGenImageToVideoGenerateResponseResponseBodyHTTPValidationError(httpValidationError components.HTTPValidationError) GenImageToVideoGenerateResponseResponseBody {
	typ := GenImageToVideoGenerateResponseResponseBodyTypeHTTPValidationError

	return GenImageToVideoGenerateResponseResponseBody{
		HTTPValidationError: &httpValidationError,
		Type:                typ,
	}
}

func CreateGenImageToVideoGenerateResponseResponseBodyStudioAPIError(studioAPIError components.StudioAPIError) GenImageToVideoGenerateResponseResponseBody {
	typ := GenImageToVideoGenerateResponseResponseBodyTypeStudioAPIError

	return GenImageToVideoGenerateResponseResponseBody{
		StudioAPIError: &studioAPIError,
		Type:           typ,
	}
}

func (u *GenImageToVideoGenerateResponseResponseBody) UnmarshalJSON(data []byte) error {

	var httpValidationError components.HTTPValidationError = components.HTTPValidationError{}
	if err := utils.UnmarshalJSON(data, &httpValidationError, "", true, nil); err == nil {
		u.HTTPValidationError = &httpValidationError
		u.Type = GenImageToVideoGenerateResponseResponseBodyTypeHTTPValidationError
		return nil
	}

	var studioAPIError components.StudioAPIError = components.StudioAPIError{}
	if err := utils.UnmarshalJSON(data, &studioAPIError, "", true, nil); err == nil {
		u.StudioAPIError = &studioAPIError
		u.Type = GenImageToVideoGenerateResponseResponseBodyTypeStudioAPIError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GenImageToVideoGenerateResponseResponseBody", string(data))
}

func (u GenImageToVideoGenerateResponseResponseBody) MarshalJSON() ([]byte, error) {
	if u.HTTPValidationError != nil {
		return utils.MarshalJSON(u.HTTPValidationError, "", true)
	}

	if u.StudioAPIError != nil {
		return utils.MarshalJSON(u.StudioAPIError, "", true)
	}

	return nil, errors.New("could not marshal union type GenImageToVideoGenerateResponseResponseBody: all fields are null")
}

func (u GenImageToVideoGenerateResponseResponseBody) Error() string {
	switch u.Type {
	case GenImageToVideoGenerateResponseResponseBodyTypeHTTPValidationError:
		data, _ := json.Marshal(u.HTTPValidationError)
		return string(data)
	case GenImageToVideoGenerateResponseResponseBodyTypeStudioAPIError:
		data, _ := json.Marshal(u.StudioAPIError)
		return string(data)
	default:
		return "unknown error"
	}
}

type GenImageToVideoGenerateResponseBodyType string

const (
	GenImageToVideoGenerateResponseBodyTypeHTTPError      GenImageToVideoGenerateResponseBodyType = "HTTPError"
	GenImageToVideoGenerateResponseBodyTypeStudioAPIError GenImageToVideoGenerateResponseBodyType = "studio-api-error"
)

// GenImageToVideoGenerateResponseBody - Unauthorized
type GenImageToVideoGenerateResponseBody struct {
	HTTPError      *components.HTTPError      `queryParam:"inline,name=responseBody"`
	StudioAPIError *components.StudioAPIError `queryParam:"inline,name=responseBody"`

	Type GenImageToVideoGenerateResponseBodyType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GenImageToVideoGenerateResponseBody{}

func CreateGenImageToVideoGenerateResponseBodyHTTPError(httpError components.HTTPError) GenImageToVideoGenerateResponseBody {
	typ := GenImageToVideoGenerateResponseBodyTypeHTTPError

	return GenImageToVideoGenerateResponseBody{
		HTTPError: &httpError,
		Type:      typ,
	}
}

func CreateGenImageToVideoGenerateResponseBodyStudioAPIError(studioAPIError components.StudioAPIError) GenImageToVideoGenerateResponseBody {
	typ := GenImageToVideoGenerateResponseBodyTypeStudioAPIError

	return GenImageToVideoGenerateResponseBody{
		StudioAPIError: &studioAPIError,
		Type:           typ,
	}
}

func (u *GenImageToVideoGenerateResponseBody) UnmarshalJSON(data []byte) error {

	var httpError components.HTTPError = components.HTTPError{}
	if err := utils.UnmarshalJSON(data, &httpError, "", true, nil); err == nil {
		u.HTTPError = &httpError
		u.Type = GenImageToVideoGenerateResponseBodyTypeHTTPError
		return nil
	}

	var studioAPIError components.StudioAPIError = components.StudioAPIError{}
	if err := utils.UnmarshalJSON(data, &studioAPIError, "", true, nil); err == nil {
		u.StudioAPIError = &studioAPIError
		u.Type = GenImageToVideoGenerateResponseBodyTypeStudioAPIError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GenImageToVideoGenerateResponseBody", string(data))
}

func (u GenImageToVideoGenerateResponseBody) MarshalJSON() ([]byte, error) {
	if u.HTTPError != nil {
		return utils.MarshalJSON(u.HTTPError, "", true)
	}

	if u.StudioAPIError != nil {
		return utils.MarshalJSON(u.StudioAPIError, "", true)
	}

	return nil, errors.New("could not marshal union type GenImageToVideoGenerateResponseBody: all fields are null")
}

func (u GenImageToVideoGenerateResponseBody) Error() string {
	switch u.Type {
	case GenImageToVideoGenerateResponseBodyTypeHTTPError:
		data, _ := json.Marshal(u.HTTPError)
		return string(data)
	case GenImageToVideoGenerateResponseBodyTypeStudioAPIError:
		data, _ := json.Marshal(u.StudioAPIError)
		return string(data)
	default:
		return "unknown error"
	}
}

type GenImageToVideoResponseBodyType string

const (
	GenImageToVideoResponseBodyTypeHTTPError      GenImageToVideoResponseBodyType = "HTTPError"
	GenImageToVideoResponseBodyTypeStudioAPIError GenImageToVideoResponseBodyType = "studio-api-error"
)

// GenImageToVideoResponseBody - Bad Request
type GenImageToVideoResponseBody struct {
	HTTPError      *components.HTTPError      `queryParam:"inline,name=responseBody"`
	StudioAPIError *components.StudioAPIError `queryParam:"inline,name=responseBody"`

	Type GenImageToVideoResponseBodyType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GenImageToVideoResponseBody{}

func CreateGenImageToVideoResponseBodyHTTPError(httpError components.HTTPError) GenImageToVideoResponseBody {
	typ := GenImageToVideoResponseBodyTypeHTTPError

	return GenImageToVideoResponseBody{
		HTTPError: &httpError,
		Type:      typ,
	}
}

func CreateGenImageToVideoResponseBodyStudioAPIError(studioAPIError components.StudioAPIError) GenImageToVideoResponseBody {
	typ := GenImageToVideoResponseBodyTypeStudioAPIError

	return GenImageToVideoResponseBody{
		StudioAPIError: &studioAPIError,
		Type:           typ,
	}
}

func (u *GenImageToVideoResponseBody) UnmarshalJSON(data []byte) error {

	var httpError components.HTTPError = components.HTTPError{}
	if err := utils.UnmarshalJSON(data, &httpError, "", true, nil); err == nil {
		u.HTTPError = &httpError
		u.Type = GenImageToVideoResponseBodyTypeHTTPError
		return nil
	}

	var studioAPIError components.StudioAPIError = components.StudioAPIError{}
	if err := utils.UnmarshalJSON(data, &studioAPIError, "", true, nil); err == nil {
		u.StudioAPIError = &studioAPIError
		u.Type = GenImageToVideoResponseBodyTypeStudioAPIError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GenImageToVideoResponseBody", string(data))
}

func (u GenImageToVideoResponseBody) MarshalJSON() ([]byte, error) {
	if u.HTTPError != nil {
		return utils.MarshalJSON(u.HTTPError, "", true)
	}

	if u.StudioAPIError != nil {
		return utils.MarshalJSON(u.StudioAPIError, "", true)
	}

	return nil, errors.New("could not marshal union type GenImageToVideoResponseBody: all fields are null")
}

func (u GenImageToVideoResponseBody) Error() string {
	switch u.Type {
	case GenImageToVideoResponseBodyTypeHTTPError:
		data, _ := json.Marshal(u.HTTPError)
		return string(data)
	case GenImageToVideoResponseBodyTypeStudioAPIError:
		data, _ := json.Marshal(u.StudioAPIError)
		return string(data)
	default:
		return "unknown error"
	}
}
