// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/livepeer/livepeer-go/internal/utils"
	"github.com/livepeer/livepeer-go/models/components"
)

type GenTextToImageGenerateResponse500ResponseBodyType string

const (
	GenTextToImageGenerateResponse500ResponseBodyTypeHTTPError      GenTextToImageGenerateResponse500ResponseBodyType = "HTTPError"
	GenTextToImageGenerateResponse500ResponseBodyTypeStudioAPIError GenTextToImageGenerateResponse500ResponseBodyType = "studio-api-error"
)

// GenTextToImageGenerateResponse500ResponseBody - Internal Server Error
type GenTextToImageGenerateResponse500ResponseBody struct {
	HTTPError      *components.HTTPError      `queryParam:"inline" name:"responseBody"`
	StudioAPIError *components.StudioAPIError `queryParam:"inline" name:"responseBody"`

	Type GenTextToImageGenerateResponse500ResponseBodyType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GenTextToImageGenerateResponse500ResponseBody{}

func CreateGenTextToImageGenerateResponse500ResponseBodyHTTPError(httpError components.HTTPError) GenTextToImageGenerateResponse500ResponseBody {
	typ := GenTextToImageGenerateResponse500ResponseBodyTypeHTTPError

	return GenTextToImageGenerateResponse500ResponseBody{
		HTTPError: &httpError,
		Type:      typ,
	}
}

func CreateGenTextToImageGenerateResponse500ResponseBodyStudioAPIError(studioAPIError components.StudioAPIError) GenTextToImageGenerateResponse500ResponseBody {
	typ := GenTextToImageGenerateResponse500ResponseBodyTypeStudioAPIError

	return GenTextToImageGenerateResponse500ResponseBody{
		StudioAPIError: &studioAPIError,
		Type:           typ,
	}
}

func (u *GenTextToImageGenerateResponse500ResponseBody) UnmarshalJSON(data []byte) error {

	var httpError components.HTTPError = components.HTTPError{}
	if err := utils.UnmarshalJSON(data, &httpError, "", true, nil); err == nil {
		u.HTTPError = &httpError
		u.Type = GenTextToImageGenerateResponse500ResponseBodyTypeHTTPError
		return nil
	}

	var studioAPIError components.StudioAPIError = components.StudioAPIError{}
	if err := utils.UnmarshalJSON(data, &studioAPIError, "", true, nil); err == nil {
		u.StudioAPIError = &studioAPIError
		u.Type = GenTextToImageGenerateResponse500ResponseBodyTypeStudioAPIError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GenTextToImageGenerateResponse500ResponseBody", string(data))
}

func (u GenTextToImageGenerateResponse500ResponseBody) MarshalJSON() ([]byte, error) {
	if u.HTTPError != nil {
		return utils.MarshalJSON(u.HTTPError, "", true)
	}

	if u.StudioAPIError != nil {
		return utils.MarshalJSON(u.StudioAPIError, "", true)
	}

	return nil, errors.New("could not marshal union type GenTextToImageGenerateResponse500ResponseBody: all fields are null")
}

func (u GenTextToImageGenerateResponse500ResponseBody) Error() string {
	switch u.Type {
	case GenTextToImageGenerateResponse500ResponseBodyTypeHTTPError:
		data, _ := json.Marshal(u.HTTPError)
		return string(data)
	case GenTextToImageGenerateResponse500ResponseBodyTypeStudioAPIError:
		data, _ := json.Marshal(u.StudioAPIError)
		return string(data)
	default:
		return "unknown error"
	}
}

type GenTextToImageGenerateResponseResponseBodyType string

const (
	GenTextToImageGenerateResponseResponseBodyTypeHTTPValidationError GenTextToImageGenerateResponseResponseBodyType = "HTTPValidationError"
	GenTextToImageGenerateResponseResponseBodyTypeStudioAPIError      GenTextToImageGenerateResponseResponseBodyType = "studio-api-error"
)

// GenTextToImageGenerateResponseResponseBody - Validation Error
type GenTextToImageGenerateResponseResponseBody struct {
	HTTPValidationError *components.HTTPValidationError `queryParam:"inline" name:"responseBody"`
	StudioAPIError      *components.StudioAPIError      `queryParam:"inline" name:"responseBody"`

	Type GenTextToImageGenerateResponseResponseBodyType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GenTextToImageGenerateResponseResponseBody{}

func CreateGenTextToImageGenerateResponseResponseBodyHTTPValidationError(httpValidationError components.HTTPValidationError) GenTextToImageGenerateResponseResponseBody {
	typ := GenTextToImageGenerateResponseResponseBodyTypeHTTPValidationError

	return GenTextToImageGenerateResponseResponseBody{
		HTTPValidationError: &httpValidationError,
		Type:                typ,
	}
}

func CreateGenTextToImageGenerateResponseResponseBodyStudioAPIError(studioAPIError components.StudioAPIError) GenTextToImageGenerateResponseResponseBody {
	typ := GenTextToImageGenerateResponseResponseBodyTypeStudioAPIError

	return GenTextToImageGenerateResponseResponseBody{
		StudioAPIError: &studioAPIError,
		Type:           typ,
	}
}

func (u *GenTextToImageGenerateResponseResponseBody) UnmarshalJSON(data []byte) error {

	var httpValidationError components.HTTPValidationError = components.HTTPValidationError{}
	if err := utils.UnmarshalJSON(data, &httpValidationError, "", true, nil); err == nil {
		u.HTTPValidationError = &httpValidationError
		u.Type = GenTextToImageGenerateResponseResponseBodyTypeHTTPValidationError
		return nil
	}

	var studioAPIError components.StudioAPIError = components.StudioAPIError{}
	if err := utils.UnmarshalJSON(data, &studioAPIError, "", true, nil); err == nil {
		u.StudioAPIError = &studioAPIError
		u.Type = GenTextToImageGenerateResponseResponseBodyTypeStudioAPIError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GenTextToImageGenerateResponseResponseBody", string(data))
}

func (u GenTextToImageGenerateResponseResponseBody) MarshalJSON() ([]byte, error) {
	if u.HTTPValidationError != nil {
		return utils.MarshalJSON(u.HTTPValidationError, "", true)
	}

	if u.StudioAPIError != nil {
		return utils.MarshalJSON(u.StudioAPIError, "", true)
	}

	return nil, errors.New("could not marshal union type GenTextToImageGenerateResponseResponseBody: all fields are null")
}

func (u GenTextToImageGenerateResponseResponseBody) Error() string {
	switch u.Type {
	case GenTextToImageGenerateResponseResponseBodyTypeHTTPValidationError:
		data, _ := json.Marshal(u.HTTPValidationError)
		return string(data)
	case GenTextToImageGenerateResponseResponseBodyTypeStudioAPIError:
		data, _ := json.Marshal(u.StudioAPIError)
		return string(data)
	default:
		return "unknown error"
	}
}

type GenTextToImageGenerateResponseBodyType string

const (
	GenTextToImageGenerateResponseBodyTypeHTTPError      GenTextToImageGenerateResponseBodyType = "HTTPError"
	GenTextToImageGenerateResponseBodyTypeStudioAPIError GenTextToImageGenerateResponseBodyType = "studio-api-error"
)

// GenTextToImageGenerateResponseBody - Unauthorized
type GenTextToImageGenerateResponseBody struct {
	HTTPError      *components.HTTPError      `queryParam:"inline" name:"responseBody"`
	StudioAPIError *components.StudioAPIError `queryParam:"inline" name:"responseBody"`

	Type GenTextToImageGenerateResponseBodyType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GenTextToImageGenerateResponseBody{}

func CreateGenTextToImageGenerateResponseBodyHTTPError(httpError components.HTTPError) GenTextToImageGenerateResponseBody {
	typ := GenTextToImageGenerateResponseBodyTypeHTTPError

	return GenTextToImageGenerateResponseBody{
		HTTPError: &httpError,
		Type:      typ,
	}
}

func CreateGenTextToImageGenerateResponseBodyStudioAPIError(studioAPIError components.StudioAPIError) GenTextToImageGenerateResponseBody {
	typ := GenTextToImageGenerateResponseBodyTypeStudioAPIError

	return GenTextToImageGenerateResponseBody{
		StudioAPIError: &studioAPIError,
		Type:           typ,
	}
}

func (u *GenTextToImageGenerateResponseBody) UnmarshalJSON(data []byte) error {

	var httpError components.HTTPError = components.HTTPError{}
	if err := utils.UnmarshalJSON(data, &httpError, "", true, nil); err == nil {
		u.HTTPError = &httpError
		u.Type = GenTextToImageGenerateResponseBodyTypeHTTPError
		return nil
	}

	var studioAPIError components.StudioAPIError = components.StudioAPIError{}
	if err := utils.UnmarshalJSON(data, &studioAPIError, "", true, nil); err == nil {
		u.StudioAPIError = &studioAPIError
		u.Type = GenTextToImageGenerateResponseBodyTypeStudioAPIError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GenTextToImageGenerateResponseBody", string(data))
}

func (u GenTextToImageGenerateResponseBody) MarshalJSON() ([]byte, error) {
	if u.HTTPError != nil {
		return utils.MarshalJSON(u.HTTPError, "", true)
	}

	if u.StudioAPIError != nil {
		return utils.MarshalJSON(u.StudioAPIError, "", true)
	}

	return nil, errors.New("could not marshal union type GenTextToImageGenerateResponseBody: all fields are null")
}

func (u GenTextToImageGenerateResponseBody) Error() string {
	switch u.Type {
	case GenTextToImageGenerateResponseBodyTypeHTTPError:
		data, _ := json.Marshal(u.HTTPError)
		return string(data)
	case GenTextToImageGenerateResponseBodyTypeStudioAPIError:
		data, _ := json.Marshal(u.StudioAPIError)
		return string(data)
	default:
		return "unknown error"
	}
}

type GenTextToImageResponseBodyType string

const (
	GenTextToImageResponseBodyTypeHTTPError      GenTextToImageResponseBodyType = "HTTPError"
	GenTextToImageResponseBodyTypeStudioAPIError GenTextToImageResponseBodyType = "studio-api-error"
)

// GenTextToImageResponseBody - Bad Request
type GenTextToImageResponseBody struct {
	HTTPError      *components.HTTPError      `queryParam:"inline" name:"responseBody"`
	StudioAPIError *components.StudioAPIError `queryParam:"inline" name:"responseBody"`

	Type GenTextToImageResponseBodyType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GenTextToImageResponseBody{}

func CreateGenTextToImageResponseBodyHTTPError(httpError components.HTTPError) GenTextToImageResponseBody {
	typ := GenTextToImageResponseBodyTypeHTTPError

	return GenTextToImageResponseBody{
		HTTPError: &httpError,
		Type:      typ,
	}
}

func CreateGenTextToImageResponseBodyStudioAPIError(studioAPIError components.StudioAPIError) GenTextToImageResponseBody {
	typ := GenTextToImageResponseBodyTypeStudioAPIError

	return GenTextToImageResponseBody{
		StudioAPIError: &studioAPIError,
		Type:           typ,
	}
}

func (u *GenTextToImageResponseBody) UnmarshalJSON(data []byte) error {

	var httpError components.HTTPError = components.HTTPError{}
	if err := utils.UnmarshalJSON(data, &httpError, "", true, nil); err == nil {
		u.HTTPError = &httpError
		u.Type = GenTextToImageResponseBodyTypeHTTPError
		return nil
	}

	var studioAPIError components.StudioAPIError = components.StudioAPIError{}
	if err := utils.UnmarshalJSON(data, &studioAPIError, "", true, nil); err == nil {
		u.StudioAPIError = &studioAPIError
		u.Type = GenTextToImageResponseBodyTypeStudioAPIError
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GenTextToImageResponseBody", string(data))
}

func (u GenTextToImageResponseBody) MarshalJSON() ([]byte, error) {
	if u.HTTPError != nil {
		return utils.MarshalJSON(u.HTTPError, "", true)
	}

	if u.StudioAPIError != nil {
		return utils.MarshalJSON(u.StudioAPIError, "", true)
	}

	return nil, errors.New("could not marshal union type GenTextToImageResponseBody: all fields are null")
}

func (u GenTextToImageResponseBody) Error() string {
	switch u.Type {
	case GenTextToImageResponseBodyTypeHTTPError:
		data, _ := json.Marshal(u.HTTPError)
		return string(data)
	case GenTextToImageResponseBodyTypeStudioAPIError:
		data, _ := json.Marshal(u.StudioAPIError)
		return string(data)
	default:
		return "unknown error"
	}
}
