// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssetPatchPayload struct {
	// The name of the asset. This is not necessarily the filename - it can be a custom name or title.
	//
	Name      *string         `json:"name,omitempty"`
	CreatorID *InputCreatorID `json:"creatorId,omitempty"`
	// Whether the playback policy for an asset or stream is public or signed
	PlaybackPolicy *PlaybackPolicy `json:"playbackPolicy,omitempty"`
	Storage        *Storage        `json:"storage,omitempty"`
}

func (a *AssetPatchPayload) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AssetPatchPayload) GetCreatorID() *InputCreatorID {
	if a == nil {
		return nil
	}
	return a.CreatorID
}

func (a *AssetPatchPayload) GetPlaybackPolicy() *PlaybackPolicy {
	if a == nil {
		return nil
	}
	return a.PlaybackPolicy
}

func (a *AssetPatchPayload) GetStorage() *Storage {
	if a == nil {
		return nil
	}
	return a.Storage
}
