// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-go/internal/utils"
)

type Audio struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (a *Audio) GetFileName() string {
	if a == nil {
		return ""
	}
	return a.FileName
}

func (a *Audio) GetContent() any {
	if a == nil {
		return nil
	}
	return a.Content
}

type BodyGenAudioToText struct {
	// Uploaded audio file to be transcribed.
	Audio Audio `multipartForm:"file,name=audio"`
	// Hugging Face model ID used for transcription.
	ModelID *string `default:"openai/whisper-large-v3" multipartForm:"name=model_id"`
	// Return timestamps for the transcribed text. Supported values: 'sentence', 'word', or a string boolean ('true' or 'false'). Default is 'true' ('sentence'). 'false' means no timestamps. 'word' means word-based timestamps.
	ReturnTimestamps *string `default:"true" multipartForm:"name=return_timestamps"`
}

func (b BodyGenAudioToText) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyGenAudioToText) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"audio"}); err != nil {
		return err
	}
	return nil
}

func (b *BodyGenAudioToText) GetAudio() Audio {
	if b == nil {
		return Audio{}
	}
	return b.Audio
}

func (b *BodyGenAudioToText) GetModelID() *string {
	if b == nil {
		return nil
	}
	return b.ModelID
}

func (b *BodyGenAudioToText) GetReturnTimestamps() *string {
	if b == nil {
		return nil
	}
	return b.ReturnTimestamps
}
