// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-go/internal/utils"
)

type BodyGenImageToTextImage struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (b *BodyGenImageToTextImage) GetFileName() string {
	if b == nil {
		return ""
	}
	return b.FileName
}

func (b *BodyGenImageToTextImage) GetContent() any {
	if b == nil {
		return nil
	}
	return b.Content
}

type BodyGenImageToText struct {
	// Uploaded image to transform with the pipeline.
	Image BodyGenImageToTextImage `multipartForm:"file,name=image"`
	// Text prompt(s) to guide transformation.
	Prompt *string `default:"" multipartForm:"name=prompt"`
	// Hugging Face model ID used for transformation.
	ModelID *string `default:"" multipartForm:"name=model_id"`
}

func (b BodyGenImageToText) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyGenImageToText) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"image"}); err != nil {
		return err
	}
	return nil
}

func (b *BodyGenImageToText) GetImage() BodyGenImageToTextImage {
	if b == nil {
		return BodyGenImageToTextImage{}
	}
	return b.Image
}

func (b *BodyGenImageToText) GetPrompt() *string {
	if b == nil {
		return nil
	}
	return b.Prompt
}

func (b *BodyGenImageToText) GetModelID() *string {
	if b == nil {
		return nil
	}
	return b.ModelID
}
