// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Chunk - A chunk of text with a timestamp.
type Chunk struct {
	// The timestamp of the chunk.
	Timestamp []any `json:"timestamp"`
	// The text of the chunk.
	Text string `json:"text"`
}

func (c *Chunk) GetTimestamp() []any {
	if c == nil {
		return []any{}
	}
	return c.Timestamp
}

func (c *Chunk) GetText() string {
	if c == nil {
		return ""
	}
	return c.Text
}
