// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ClipPayload struct {
	// Playback ID of the stream or asset to clip
	PlaybackID string `json:"playbackId"`
	// Start time of the clip in milliseconds
	StartTime float64 `json:"startTime"`
	// End time of the clip in milliseconds
	EndTime *float64 `json:"endTime,omitempty"`
	// Name of the clip
	Name *string `json:"name,omitempty"`
	// Session ID of the stream to clip
	SessionID *string `json:"sessionId,omitempty"`
}

func (o *ClipPayload) GetPlaybackID() string {
	if o == nil {
		return ""
	}
	return o.PlaybackID
}

func (o *ClipPayload) GetStartTime() float64 {
	if o == nil {
		return 0.0
	}
	return o.StartTime
}

func (o *ClipPayload) GetEndTime() *float64 {
	if o == nil {
		return nil
	}
	return o.EndTime
}

func (o *ClipPayload) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ClipPayload) GetSessionID() *string {
	if o == nil {
		return nil
	}
	return o.SessionID
}
