// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/livepeer/livepeer-go/internal/utils"
)

type ExportTaskParams2 struct {
	Ipfs IpfsExportParams `json:"ipfs"`
}

func (e ExportTaskParams2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExportTaskParams2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"ipfs"}); err != nil {
		return err
	}
	return nil
}

func (e *ExportTaskParams2) GetIpfs() IpfsExportParams {
	if e == nil {
		return IpfsExportParams{}
	}
	return e.Ipfs
}

// Custom - custom URL parameters for the export task
type Custom struct {
	// URL where to export the asset
	URL string `json:"url"`
	// Method to use on the export request
	Method *string `default:"PUT" json:"method"`
	// Headers to add to the export request
	Headers map[string]string `json:"headers,omitempty"`
}

func (c Custom) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Custom) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"url"}); err != nil {
		return err
	}
	return nil
}

func (c *Custom) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

func (c *Custom) GetMethod() *string {
	if c == nil {
		return nil
	}
	return c.Method
}

func (c *Custom) GetHeaders() map[string]string {
	if c == nil {
		return nil
	}
	return c.Headers
}

type ExportTaskParams1 struct {
	// custom URL parameters for the export task
	Custom Custom `json:"custom"`
}

func (e ExportTaskParams1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExportTaskParams1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"custom"}); err != nil {
		return err
	}
	return nil
}

func (e *ExportTaskParams1) GetCustom() Custom {
	if e == nil {
		return Custom{}
	}
	return e.Custom
}

type ExportTaskParamsType string

const (
	ExportTaskParamsTypeExportTaskParams1 ExportTaskParamsType = "export-task-params_1"
	ExportTaskParamsTypeExportTaskParams2 ExportTaskParamsType = "export-task-params_2"
)

// ExportTaskParams - Parameters for the export task
type ExportTaskParams struct {
	ExportTaskParams1 *ExportTaskParams1 `queryParam:"inline" name:"export_task_params"`
	ExportTaskParams2 *ExportTaskParams2 `queryParam:"inline" name:"export_task_params"`

	Type ExportTaskParamsType
}

func CreateExportTaskParamsExportTaskParams1(exportTaskParams1 ExportTaskParams1) ExportTaskParams {
	typ := ExportTaskParamsTypeExportTaskParams1

	return ExportTaskParams{
		ExportTaskParams1: &exportTaskParams1,
		Type:              typ,
	}
}

func CreateExportTaskParamsExportTaskParams2(exportTaskParams2 ExportTaskParams2) ExportTaskParams {
	typ := ExportTaskParamsTypeExportTaskParams2

	return ExportTaskParams{
		ExportTaskParams2: &exportTaskParams2,
		Type:              typ,
	}
}

func (u *ExportTaskParams) UnmarshalJSON(data []byte) error {

	var exportTaskParams1 ExportTaskParams1 = ExportTaskParams1{}
	if err := utils.UnmarshalJSON(data, &exportTaskParams1, "", true, nil); err == nil {
		u.ExportTaskParams1 = &exportTaskParams1
		u.Type = ExportTaskParamsTypeExportTaskParams1
		return nil
	}

	var exportTaskParams2 ExportTaskParams2 = ExportTaskParams2{}
	if err := utils.UnmarshalJSON(data, &exportTaskParams2, "", true, nil); err == nil {
		u.ExportTaskParams2 = &exportTaskParams2
		u.Type = ExportTaskParamsTypeExportTaskParams2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ExportTaskParams", string(data))
}

func (u ExportTaskParams) MarshalJSON() ([]byte, error) {
	if u.ExportTaskParams1 != nil {
		return utils.MarshalJSON(u.ExportTaskParams1, "", true)
	}

	if u.ExportTaskParams2 != nil {
		return utils.MarshalJSON(u.ExportTaskParams2, "", true)
	}

	return nil, errors.New("could not marshal union type ExportTaskParams: all fields are null")
}
