// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IpfsFileInfo struct {
	// CID of the file on IPFS
	Cid string `json:"cid"`
	// URL with IPFS scheme for the file
	URL *string `json:"url,omitempty"`
	// URL to access file via HTTP through an IPFS gateway
	GatewayURL *string `json:"gatewayUrl,omitempty"`
}

func (i *IpfsFileInfo) GetCid() string {
	if i == nil {
		return ""
	}
	return i.Cid
}

func (i *IpfsFileInfo) GetURL() *string {
	if i == nil {
		return nil
	}
	return i.URL
}

func (i *IpfsFileInfo) GetGatewayURL() *string {
	if i == nil {
		return nil
	}
	return i.GatewayURL
}
