// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type IpfsFileInfoInput struct {
	// CID of the file on IPFS
	Cid string `json:"cid"`
}

func (o *IpfsFileInfoInput) GetCid() string {
	if o == nil {
		return ""
	}
	return o.Cid
}
