// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-go/internal/utils"
)

// LiveVideoToVideoParamsParams - Initial parameters for the pipeline.
type LiveVideoToVideoParamsParams struct {
}

type LiveVideoToVideoParams struct {
	// Source URL of the incoming stream to subscribe to.
	SubscribeURL string `json:"subscribe_url"`
	// Destination URL of the outgoing stream to publish.
	PublishURL string `json:"publish_url"`
	// URL for subscribing via Trickle protocol for updates in the live video-to-video generation params.
	ControlURL *string `default:"" json:"control_url"`
	// URL for publishing events via Trickle protocol for pipeline status and logs.
	EventsURL *string `default:"" json:"events_url"`
	// Name of the pipeline to run in the live video to video job. Notice that this is named model_id for consistency with other routes, but it does not refer to a Hugging Face model ID. The exact model(s) depends on the pipeline implementation and might be configurable via the `params` argument.
	ModelID *string `default:"" json:"model_id"`
	// Initial parameters for the pipeline.
	Params *LiveVideoToVideoParamsParams `json:"params,omitempty"`
	// The ID of the Gateway request (for logging purposes).
	GatewayRequestID *string `default:"" json:"gateway_request_id"`
	// The manifest ID from the orchestrator (for logging purposes).
	ManifestID *string `default:"" json:"manifest_id"`
	// The Stream ID (for logging purposes).
	StreamID *string `default:"" json:"stream_id"`
}

func (l LiveVideoToVideoParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LiveVideoToVideoParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"subscribe_url", "publish_url"}); err != nil {
		return err
	}
	return nil
}

func (l *LiveVideoToVideoParams) GetSubscribeURL() string {
	if l == nil {
		return ""
	}
	return l.SubscribeURL
}

func (l *LiveVideoToVideoParams) GetPublishURL() string {
	if l == nil {
		return ""
	}
	return l.PublishURL
}

func (l *LiveVideoToVideoParams) GetControlURL() *string {
	if l == nil {
		return nil
	}
	return l.ControlURL
}

func (l *LiveVideoToVideoParams) GetEventsURL() *string {
	if l == nil {
		return nil
	}
	return l.EventsURL
}

func (l *LiveVideoToVideoParams) GetModelID() *string {
	if l == nil {
		return nil
	}
	return l.ModelID
}

func (l *LiveVideoToVideoParams) GetParams() *LiveVideoToVideoParamsParams {
	if l == nil {
		return nil
	}
	return l.Params
}

func (l *LiveVideoToVideoParams) GetGatewayRequestID() *string {
	if l == nil {
		return nil
	}
	return l.GatewayRequestID
}

func (l *LiveVideoToVideoParams) GetManifestID() *string {
	if l == nil {
		return nil
	}
	return l.ManifestID
}

func (l *LiveVideoToVideoParams) GetStreamID() *string {
	if l == nil {
		return nil
	}
	return l.StreamID
}
