// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-go/internal/utils"
)

type LLMChoice struct {
	Index        int64       `json:"index"`
	FinishReason *string     `default:"" json:"finish_reason"`
	Delta        *LLMMessage `json:"delta,omitempty"`
	Message      *LLMMessage `json:"message,omitempty"`
}

func (l LLMChoice) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LLMChoice) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"index"}); err != nil {
		return err
	}
	return nil
}

func (l *LLMChoice) GetIndex() int64 {
	if l == nil {
		return 0
	}
	return l.Index
}

func (l *LLMChoice) GetFinishReason() *string {
	if l == nil {
		return nil
	}
	return l.FinishReason
}

func (l *LLMChoice) GetDelta() *LLMMessage {
	if l == nil {
		return nil
	}
	return l.Delta
}

func (l *LLMChoice) GetMessage() *LLMMessage {
	if l == nil {
		return nil
	}
	return l.Message
}
