// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-go/internal/utils"
)

type LLMRequest struct {
	Messages    []LLMMessage `json:"messages"`
	Model       *string      `default:"" json:"model"`
	Temperature *float64     `default:"0.7" json:"temperature"`
	MaxTokens   *int64       `default:"256" json:"max_tokens"`
	TopP        *float64     `default:"1" json:"top_p"`
	TopK        *int64       `default:"-1" json:"top_k"`
	Stream      *bool        `default:"false" json:"stream"`
}

func (l LLMRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LLMRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"messages"}); err != nil {
		return err
	}
	return nil
}

func (l *LLMRequest) GetMessages() []LLMMessage {
	if l == nil {
		return []LLMMessage{}
	}
	return l.Messages
}

func (l *LLMRequest) GetModel() *string {
	if l == nil {
		return nil
	}
	return l.Model
}

func (l *LLMRequest) GetTemperature() *float64 {
	if l == nil {
		return nil
	}
	return l.Temperature
}

func (l *LLMRequest) GetMaxTokens() *int64 {
	if l == nil {
		return nil
	}
	return l.MaxTokens
}

func (l *LLMRequest) GetTopP() *float64 {
	if l == nil {
		return nil
	}
	return l.TopP
}

func (l *LLMRequest) GetTopK() *int64 {
	if l == nil {
		return nil
	}
	return l.TopK
}

func (l *LLMRequest) GetStream() *bool {
	if l == nil {
		return nil
	}
	return l.Stream
}
