// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MasksResponse - Response model for object segmentation.
type MasksResponse struct {
	// The generated masks.
	Masks string `json:"masks"`
	// The model's confidence scores for each generated mask.
	Scores string `json:"scores"`
	// The raw, unnormalized predictions (logits) for the masks.
	Logits string `json:"logits"`
}

func (m *MasksResponse) GetMasks() string {
	if m == nil {
		return ""
	}
	return m.Masks
}

func (m *MasksResponse) GetScores() string {
	if m == nil {
		return ""
	}
	return m.Scores
}

func (m *MasksResponse) GetLogits() string {
	if m == nil {
		return ""
	}
	return m.Logits
}
