// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Multistream struct {
	// References to targets where this stream will be simultaneously
	// streamed to
	//
	Targets []Target `json:"targets,omitempty"`
}

func (o *Multistream) GetTargets() []Target {
	if o == nil {
		return nil
	}
	return o.Targets
}
