// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NewAssetFromURLPayload struct {
	// The name of the asset. This is not necessarily the filename - it can be a custom name or title.
	//
	Name string `json:"name"`
	// Whether to generate MP4s for the asset.
	StaticMp4 *bool `json:"staticMp4,omitempty"`
	// Whether the playback policy for an asset or stream is public or signed
	PlaybackPolicy *PlaybackPolicy `json:"playbackPolicy,omitempty"`
	CreatorID      *InputCreatorID `json:"creatorId,omitempty"`
	Storage        *Storage        `json:"storage,omitempty"`
	// URL where the asset contents can be retrieved, e.g. `https://s3.amazonaws.com/my-bucket/path/filename.mp4`.
	// For an IPFS source, this should be similar to: `ipfs://{CID}`. For an Arweave
	// source: `ar://{CID}`.
	//
	URL        string      `json:"url"`
	Encryption *Encryption `json:"encryption,omitempty"`
	// Decides if the output video should include C2PA signature
	C2pa     *bool              `json:"c2pa,omitempty"`
	Profiles []TranscodeProfile `json:"profiles,omitempty"`
	// How many seconds the duration of each output segment should be
	TargetSegmentSizeSecs *float64 `json:"targetSegmentSizeSecs,omitempty"`
}

func (n *NewAssetFromURLPayload) GetName() string {
	if n == nil {
		return ""
	}
	return n.Name
}

func (n *NewAssetFromURLPayload) GetStaticMp4() *bool {
	if n == nil {
		return nil
	}
	return n.StaticMp4
}

func (n *NewAssetFromURLPayload) GetPlaybackPolicy() *PlaybackPolicy {
	if n == nil {
		return nil
	}
	return n.PlaybackPolicy
}

func (n *NewAssetFromURLPayload) GetCreatorID() *InputCreatorID {
	if n == nil {
		return nil
	}
	return n.CreatorID
}

func (n *NewAssetFromURLPayload) GetStorage() *Storage {
	if n == nil {
		return nil
	}
	return n.Storage
}

func (n *NewAssetFromURLPayload) GetURL() string {
	if n == nil {
		return ""
	}
	return n.URL
}

func (n *NewAssetFromURLPayload) GetEncryption() *Encryption {
	if n == nil {
		return nil
	}
	return n.Encryption
}

func (n *NewAssetFromURLPayload) GetC2pa() *bool {
	if n == nil {
		return nil
	}
	return n.C2pa
}

func (n *NewAssetFromURLPayload) GetProfiles() []TranscodeProfile {
	if n == nil {
		return nil
	}
	return n.Profiles
}

func (n *NewAssetFromURLPayload) GetTargetSegmentSizeSecs() *float64 {
	if n == nil {
		return nil
	}
	return n.TargetSegmentSizeSecs
}
