// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// NftMetadataTemplate - Name of the NFT metadata template to export. 'player'
// will embed the Livepeer Player on the NFT while 'file'
// will reference only the immutable MP4 files.
type NftMetadataTemplate string

const (
	NftMetadataTemplateFile   NftMetadataTemplate = "file"
	NftMetadataTemplatePlayer NftMetadataTemplate = "player"
)

func (e NftMetadataTemplate) ToPointer() *NftMetadataTemplate {
	return &e
}

func (e *NftMetadataTemplate) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "file":
		fallthrough
	case "player":
		*e = NftMetadataTemplate(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NftMetadataTemplate: %v", v)
	}
}
