// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// NftMetadata - Additional data to add to the NFT metadata exported to
// IPFS. Will be deep merged with the default metadata
// exported.
type NftMetadata struct {
}
