// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/livepeer/livepeer-go/internal/utils"
)

// IsMobile1 - 0: not mobile, 1: mobile screen share, 2: mobile camera.
type IsMobile1 int64

const (
	IsMobile1Zero IsMobile1 = 0
	IsMobile1One  IsMobile1 = 1
	IsMobile1Two  IsMobile1 = 2
)

func (e IsMobile1) ToPointer() *IsMobile1 {
	return &e
}
func (e *IsMobile1) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		fallthrough
	case 2:
		*e = IsMobile1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IsMobile1: %v", v)
	}
}

type IsMobileType string

const (
	IsMobileTypeIsMobile1 IsMobileType = "isMobile_1"
	IsMobileTypeBoolean   IsMobileType = "boolean"
)

// IsMobile - Indicates whether the stream will be pulled from a mobile source.
type IsMobile struct {
	IsMobile1 *IsMobile1
	Boolean   *bool

	Type IsMobileType
}

func CreateIsMobileIsMobile1(isMobile1 IsMobile1) IsMobile {
	typ := IsMobileTypeIsMobile1

	return IsMobile{
		IsMobile1: &isMobile1,
		Type:      typ,
	}
}

func CreateIsMobileBoolean(boolean bool) IsMobile {
	typ := IsMobileTypeBoolean

	return IsMobile{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *IsMobile) UnmarshalJSON(data []byte) error {

	var isMobile1 IsMobile1 = IsMobile1(0)
	if err := utils.UnmarshalJSON(data, &isMobile1, "", true, true); err == nil {
		u.IsMobile1 = &isMobile1
		u.Type = IsMobileTypeIsMobile1
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, true); err == nil {
		u.Boolean = &boolean
		u.Type = IsMobileTypeBoolean
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for IsMobile", string(data))
}

func (u IsMobile) MarshalJSON() ([]byte, error) {
	if u.IsMobile1 != nil {
		return utils.MarshalJSON(u.IsMobile1, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type IsMobile: all fields are null")
}

// Location - Approximate location of the pull source. The location is used to
// determine the closest Livepeer region to pull the stream from.
type Location struct {
	// Latitude of the pull source in degrees. North is positive,
	// south is negative.
	Lat float64 `json:"lat"`
	// Longitude of the pull source in degrees. East is positive,
	// west is negative.
	Lon float64 `json:"lon"`
}

func (o *Location) GetLat() float64 {
	if o == nil {
		return 0.0
	}
	return o.Lat
}

func (o *Location) GetLon() float64 {
	if o == nil {
		return 0.0
	}
	return o.Lon
}

// Pull - Configuration for a stream that should be actively pulled from an
// external source, rather than pushed to Livepeer. If specified, the
// stream will not have a streamKey.
type Pull struct {
	// Headers to be sent with the request to the pull source.
	Headers map[string]string `json:"headers,omitempty"`
	// Indicates whether the stream will be pulled from a mobile source.
	IsMobile *IsMobile `json:"isMobile,omitempty"`
	// Approximate location of the pull source. The location is used to
	// determine the closest Livepeer region to pull the stream from.
	Location *Location `json:"location,omitempty"`
	// URL from which to pull from.
	Source string `json:"source"`
}

func (o *Pull) GetHeaders() map[string]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *Pull) GetIsMobile() *IsMobile {
	if o == nil {
		return nil
	}
	return o.IsMobile
}

func (o *Pull) GetLocation() *Location {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *Pull) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}
