// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// RealtimeViewershipMetric - An individual metric about realtime viewership of a stream/asset.
type RealtimeViewershipMetric struct {
	// The playback ID associated with the metric.
	PlaybackID *string `json:"playbackId,omitempty"`
	// The device used by the viewer.
	Device *string `json:"device,omitempty"`
	// The browser used by the viewer.
	Browser *string `json:"browser,omitempty"`
	// The country where the viewer is located.
	Country *string `json:"country,omitempty"`
	// The number of views for the stream/asset.
	ViewCount int64 `json:"viewCount"`
	// The error rate for the stream/asset.
	ErrorRate float64 `json:"errorRate"`
}

func (o *RealtimeViewershipMetric) GetPlaybackID() *string {
	if o == nil {
		return nil
	}
	return o.PlaybackID
}

func (o *RealtimeViewershipMetric) GetDevice() *string {
	if o == nil {
		return nil
	}
	return o.Device
}

func (o *RealtimeViewershipMetric) GetBrowser() *string {
	if o == nil {
		return nil
	}
	return o.Browser
}

func (o *RealtimeViewershipMetric) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *RealtimeViewershipMetric) GetViewCount() int64 {
	if o == nil {
		return 0
	}
	return o.ViewCount
}

func (o *RealtimeViewershipMetric) GetErrorRate() float64 {
	if o == nil {
		return 0.0
	}
	return o.ErrorRate
}
