// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RoomEgressPayload struct {
	// The ID of the Livepeer Stream to stream to
	StreamID string `json:"streamId"`
}

func (r *RoomEgressPayload) GetStreamID() string {
	if r == nil {
		return ""
	}
	return r.StreamID
}
