// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type RoomUserPayload struct {
	// Display name
	Name string `json:"name"`
	// Whether a user is allowed to publish audio/video tracks
	CanPublish *bool `json:"canPublish,omitempty"`
	// Whether a user is allowed to publish data messages to the room
	CanPublishData *bool `json:"canPublishData,omitempty"`
	// User defined payload to store for the participant
	Metadata *string `json:"metadata,omitempty"`
}

func (o *RoomUserPayload) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RoomUserPayload) GetCanPublish() *bool {
	if o == nil {
		return nil
	}
	return o.CanPublish
}

func (o *RoomUserPayload) GetCanPublishData() *bool {
	if o == nil {
		return nil
	}
	return o.CanPublishData
}

func (o *RoomUserPayload) GetMetadata() *string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
