// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RoomUserPayload struct {
	// Display name
	Name string `json:"name"`
	// Whether a user is allowed to publish audio/video tracks
	CanPublish *bool `json:"canPublish,omitempty"`
	// Whether a user is allowed to publish data messages to the room
	CanPublishData *bool `json:"canPublishData,omitempty"`
	// User defined payload to store for the participant
	Metadata *string `json:"metadata,omitempty"`
}

func (r *RoomUserPayload) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RoomUserPayload) GetCanPublish() *bool {
	if r == nil {
		return nil
	}
	return r.CanPublish
}

func (r *RoomUserPayload) GetCanPublishData() *bool {
	if r == nil {
		return nil
	}
	return r.CanPublishData
}

func (r *RoomUserPayload) GetMetadata() *string {
	if r == nil {
		return nil
	}
	return r.Metadata
}
