// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// RecordingStatus - The status of the recording process of this stream session.
type RecordingStatus string

const (
	RecordingStatusWaiting RecordingStatus = "waiting"
	RecordingStatusReady   RecordingStatus = "ready"
	RecordingStatusFailed  RecordingStatus = "failed"
	RecordingStatusDeleted RecordingStatus = "deleted"
	RecordingStatusNone    RecordingStatus = "none"
)

func (e RecordingStatus) ToPointer() *RecordingStatus {
	return &e
}
func (e *RecordingStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "waiting":
		fallthrough
	case "ready":
		fallthrough
	case "failed":
		fallthrough
	case "deleted":
		fallthrough
	case "none":
		*e = RecordingStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecordingStatus: %v", v)
	}
}

type Session struct {
	ID *string `json:"id,omitempty"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Kind *string `json:"kind,omitempty"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	UserID             *string  `json:"userId,omitempty"`
	Name               string   `json:"name"`
	LastSeen           *float64 `json:"lastSeen,omitempty"`
	SourceSegments     *float64 `json:"sourceSegments,omitempty"`
	TranscodedSegments *float64 `json:"transcodedSegments,omitempty"`
	// Duration of all the source segments, sec
	SourceSegmentsDuration *float64 `json:"sourceSegmentsDuration,omitempty"`
	// Duration of all the transcoded segments, sec
	TranscodedSegmentsDuration *float64 `json:"transcodedSegmentsDuration,omitempty"`
	SourceBytes                *float64 `json:"sourceBytes,omitempty"`
	TranscodedBytes            *float64 `json:"transcodedBytes,omitempty"`
	// Rate at which sourceBytes increases (bytes/second)
	IngestRate *float64 `json:"ingestRate,omitempty"`
	// Rate at which transcodedBytes increases (bytes/second)
	OutgoingRate *float64 `json:"outgoingRate,omitempty"`
	// Indicates whether the stream is healthy or not.
	IsHealthy *bool `json:"isHealthy,omitempty"`
	// A string array of human-readable errors describing issues affecting the stream, if any.
	Issues []string `json:"issues,omitempty"`
	// Timestamp (in milliseconds) at which stream object was created
	CreatedAt *float64 `json:"createdAt,omitempty"`
	// Points to parent stream object
	ParentID *string `json:"parentId,omitempty"`
	// The ID of the project
	ProjectID *string `json:"projectId,omitempty"`
	// Whether the stream should be recorded. Uses default settings. For more customization, create and configure an object store.
	//
	Record *bool `json:"record,omitempty"`
	// The status of the recording process of this stream session.
	RecordingStatus *RecordingStatus `json:"recordingStatus,omitempty"`
	// URL for accessing the recording of this stream session.
	RecordingURL *string `json:"recordingUrl,omitempty"`
	// The URL for the stream session recording packaged in an MP4.
	Mp4URL *string `json:"mp4Url,omitempty"`
	// The playback ID to use with the Playback Info endpoint to retrieve playback URLs.
	PlaybackID *string `json:"playbackId,omitempty"`
	// Profiles to transcode the stream into. If not specified, a default
	// set of profiles will be used with 240p, 360p, 480p and 720p
	// resolutions. Keep in mind that the source rendition is always kept.
	//
	Profiles []FfmpegProfile `json:"profiles,omitempty"`
	// Configuration for recording the stream. This can only be set if
	// `record` is true.
	//
	RecordingSpec *RecordingSpec `json:"recordingSpec,omitempty"`
}

func (s *Session) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *Session) GetKind() *string {
	if s == nil {
		return nil
	}
	return s.Kind
}

func (s *Session) GetUserID() *string {
	if s == nil {
		return nil
	}
	return s.UserID
}

func (s *Session) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Session) GetLastSeen() *float64 {
	if s == nil {
		return nil
	}
	return s.LastSeen
}

func (s *Session) GetSourceSegments() *float64 {
	if s == nil {
		return nil
	}
	return s.SourceSegments
}

func (s *Session) GetTranscodedSegments() *float64 {
	if s == nil {
		return nil
	}
	return s.TranscodedSegments
}

func (s *Session) GetSourceSegmentsDuration() *float64 {
	if s == nil {
		return nil
	}
	return s.SourceSegmentsDuration
}

func (s *Session) GetTranscodedSegmentsDuration() *float64 {
	if s == nil {
		return nil
	}
	return s.TranscodedSegmentsDuration
}

func (s *Session) GetSourceBytes() *float64 {
	if s == nil {
		return nil
	}
	return s.SourceBytes
}

func (s *Session) GetTranscodedBytes() *float64 {
	if s == nil {
		return nil
	}
	return s.TranscodedBytes
}

func (s *Session) GetIngestRate() *float64 {
	if s == nil {
		return nil
	}
	return s.IngestRate
}

func (s *Session) GetOutgoingRate() *float64 {
	if s == nil {
		return nil
	}
	return s.OutgoingRate
}

func (s *Session) GetIsHealthy() *bool {
	if s == nil {
		return nil
	}
	return s.IsHealthy
}

func (s *Session) GetIssues() []string {
	if s == nil {
		return nil
	}
	return s.Issues
}

func (s *Session) GetCreatedAt() *float64 {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *Session) GetParentID() *string {
	if s == nil {
		return nil
	}
	return s.ParentID
}

func (s *Session) GetProjectID() *string {
	if s == nil {
		return nil
	}
	return s.ProjectID
}

func (s *Session) GetRecord() *bool {
	if s == nil {
		return nil
	}
	return s.Record
}

func (s *Session) GetRecordingStatus() *RecordingStatus {
	if s == nil {
		return nil
	}
	return s.RecordingStatus
}

func (s *Session) GetRecordingURL() *string {
	if s == nil {
		return nil
	}
	return s.RecordingURL
}

func (s *Session) GetMp4URL() *string {
	if s == nil {
		return nil
	}
	return s.Mp4URL
}

func (s *Session) GetPlaybackID() *string {
	if s == nil {
		return nil
	}
	return s.PlaybackID
}

func (s *Session) GetProfiles() []FfmpegProfile {
	if s == nil {
		return nil
	}
	return s.Profiles
}

func (s *Session) GetRecordingSpec() *RecordingSpec {
	if s == nil {
		return nil
	}
	return s.RecordingSpec
}
