// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StudioAPIError struct {
	Errors []string `json:"errors,omitempty"`
}

func (o *StudioAPIError) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}
