// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/livepeer/livepeer-go/internal/utils"
)

type TargetOutput struct {
	// Name of transcoding profile that should be sent. Use
	// "source" for pushing source stream data
	//
	Profile string `json:"profile"`
	// If true, the stream audio will be muted and only silent
	// video will be pushed to the target.
	//
	VideoOnly *bool `default:"false" json:"videoOnly"`
	// ID of multistream target object where to push this stream
	ID *string `json:"id,omitempty"`
}

func (t TargetOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TargetOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"profile"}); err != nil {
		return err
	}
	return nil
}

func (t *TargetOutput) GetProfile() string {
	if t == nil {
		return ""
	}
	return t.Profile
}

func (t *TargetOutput) GetVideoOnly() *bool {
	if t == nil {
		return nil
	}
	return t.VideoOnly
}

func (t *TargetOutput) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}
