// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TranscodeProfileProfile string

const (
	TranscodeProfileProfileH264Baseline        TranscodeProfileProfile = "H264Baseline"
	TranscodeProfileProfileH264Main            TranscodeProfileProfile = "H264Main"
	TranscodeProfileProfileH264High            TranscodeProfileProfile = "H264High"
	TranscodeProfileProfileH264ConstrainedHigh TranscodeProfileProfile = "H264ConstrainedHigh"
)

func (e TranscodeProfileProfile) ToPointer() *TranscodeProfileProfile {
	return &e
}
func (e *TranscodeProfileProfile) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "H264Baseline":
		fallthrough
	case "H264Main":
		fallthrough
	case "H264High":
		fallthrough
	case "H264ConstrainedHigh":
		*e = TranscodeProfileProfile(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TranscodeProfileProfile: %v", v)
	}
}

type TranscodeProfileEncoder string

const (
	TranscodeProfileEncoderH264 TranscodeProfileEncoder = "H.264"
	TranscodeProfileEncoderHevc TranscodeProfileEncoder = "HEVC"
	TranscodeProfileEncoderVp8  TranscodeProfileEncoder = "VP8"
	TranscodeProfileEncoderVp9  TranscodeProfileEncoder = "VP9"
)

func (e TranscodeProfileEncoder) ToPointer() *TranscodeProfileEncoder {
	return &e
}
func (e *TranscodeProfileEncoder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "H.264":
		fallthrough
	case "HEVC":
		fallthrough
	case "VP8":
		fallthrough
	case "VP9":
		*e = TranscodeProfileEncoder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TranscodeProfileEncoder: %v", v)
	}
}

// TranscodeProfile - Transcode API profile
type TranscodeProfile struct {
	Width   *int64  `json:"width,omitempty"`
	Name    *string `json:"name,omitempty"`
	Height  *int64  `json:"height,omitempty"`
	Bitrate int64   `json:"bitrate"`
	// Restricts the size of the output video using the constant quality feature. Increasing this value will result in a lower quality video. Note that this parameter might not work if the transcoder lacks support for it.
	//
	Quality *int64                   `json:"quality,omitempty"`
	Fps     *int64                   `json:"fps,omitempty"`
	FpsDen  *int64                   `json:"fpsDen,omitempty"`
	Gop     *string                  `json:"gop,omitempty"`
	Profile *TranscodeProfileProfile `json:"profile,omitempty"`
	Encoder *TranscodeProfileEncoder `json:"encoder,omitempty"`
}

func (t *TranscodeProfile) GetWidth() *int64 {
	if t == nil {
		return nil
	}
	return t.Width
}

func (t *TranscodeProfile) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TranscodeProfile) GetHeight() *int64 {
	if t == nil {
		return nil
	}
	return t.Height
}

func (t *TranscodeProfile) GetBitrate() int64 {
	if t == nil {
		return 0
	}
	return t.Bitrate
}

func (t *TranscodeProfile) GetQuality() *int64 {
	if t == nil {
		return nil
	}
	return t.Quality
}

func (t *TranscodeProfile) GetFps() *int64 {
	if t == nil {
		return nil
	}
	return t.Fps
}

func (t *TranscodeProfile) GetFpsDen() *int64 {
	if t == nil {
		return nil
	}
	return t.FpsDen
}

func (t *TranscodeProfile) GetGop() *string {
	if t == nil {
		return nil
	}
	return t.Gop
}

func (t *TranscodeProfile) GetProfile() *TranscodeProfileProfile {
	if t == nil {
		return nil
	}
	return t.Profile
}

func (t *TranscodeProfile) GetEncoder() *TranscodeProfileEncoder {
	if t == nil {
		return nil
	}
	return t.Encoder
}
