// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UsageMetric - An individual metric about usage of a user.
type UsageMetric struct {
	// The user ID associated with the metric
	UserID *string `json:"UserID,omitempty"`
	// The creator ID associated with the metric
	CreatorID *string `json:"CreatorID,omitempty"`
	// Total minutes of delivery usage.
	DeliveryUsageMins *float64 `json:"DeliveryUsageMins,omitempty"`
	// Total transcoded minutes.
	TotalUsageMins *float64 `json:"TotalUsageMins,omitempty"`
	// Total minutes of storage usage.
	StorageUsageMins *float64 `json:"StorageUsageMins,omitempty"`
}

func (u *UsageMetric) GetUserID() *string {
	if u == nil {
		return nil
	}
	return u.UserID
}

func (u *UsageMetric) GetCreatorID() *string {
	if u == nil {
		return nil
	}
	return u.CreatorID
}

func (u *UsageMetric) GetDeliveryUsageMins() *float64 {
	if u == nil {
		return nil
	}
	return u.DeliveryUsageMins
}

func (u *UsageMetric) GetTotalUsageMins() *float64 {
	if u == nil {
		return nil
	}
	return u.TotalUsageMins
}

func (u *UsageMetric) GetStorageUsageMins() *float64 {
	if u == nil {
		return nil
	}
	return u.StorageUsageMins
}
