// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VideoResponse - Response model for image generation.
type VideoResponse struct {
	// The generated images.
	Images []Media `json:"images"`
}

func (o *VideoResponse) GetImages() []Media {
	if o == nil {
		return []Media{}
	}
	return o.Images
}
