// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Request struct {
	// URL used for the request
	URL *string `json:"url,omitempty"`
	// HTTP request method
	Method *string `json:"method,omitempty"`
	// HTTP request headers
	Headers map[string]string `json:"headers,omitempty"`
	// request body
	Body *string `json:"body,omitempty"`
}

func (r *Request) GetURL() *string {
	if r == nil {
		return nil
	}
	return r.URL
}

func (r *Request) GetMethod() *string {
	if r == nil {
		return nil
	}
	return r.Method
}

func (r *Request) GetHeaders() map[string]string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *Request) GetBody() *string {
	if r == nil {
		return nil
	}
	return r.Body
}

type Response struct {
	// response body
	Body *string `json:"body,omitempty"`
	// HTTP status code
	Status *float64 `json:"status,omitempty"`
	// response status text
	StatusText *string `json:"statusText,omitempty"`
}

func (r *Response) GetBody() *string {
	if r == nil {
		return nil
	}
	return r.Body
}

func (r *Response) GetStatus() *float64 {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *Response) GetStatusText() *string {
	if r == nil {
		return nil
	}
	return r.StatusText
}

type WebhookLog struct {
	ID string `json:"id"`
	// ID of the webhook this request was made for
	WebhookID string `json:"webhookId"`
	// The event type that triggered the webhook request
	Event *string `json:"event,omitempty"`
	// Timestamp (in milliseconds) at which webhook request object was
	// created
	//
	CreatedAt *float64 `json:"createdAt,omitempty"`
	// The time taken (in seconds) to make the webhook request
	Duration *float64 `json:"duration,omitempty"`
	// Whether the webhook request was successful
	Success  *bool     `json:"success,omitempty"`
	Request  *Request  `json:"request,omitempty"`
	Response *Response `json:"response,omitempty"`
}

func (w *WebhookLog) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WebhookLog) GetWebhookID() string {
	if w == nil {
		return ""
	}
	return w.WebhookID
}

func (w *WebhookLog) GetEvent() *string {
	if w == nil {
		return nil
	}
	return w.Event
}

func (w *WebhookLog) GetCreatedAt() *float64 {
	if w == nil {
		return nil
	}
	return w.CreatedAt
}

func (w *WebhookLog) GetDuration() *float64 {
	if w == nil {
		return nil
	}
	return w.Duration
}

func (w *WebhookLog) GetSuccess() *bool {
	if w == nil {
		return nil
	}
	return w.Success
}

func (w *WebhookLog) GetRequest() *Request {
	if w == nil {
		return nil
	}
	return w.Request
}

func (w *WebhookLog) GetResponse() *Response {
	if w == nil {
		return nil
	}
	return w.Response
}
