// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type Events string

const (
	EventsStreamStarted           Events = "stream.started"
	EventsStreamDetection         Events = "stream.detection"
	EventsStreamIdle              Events = "stream.idle"
	EventsRecordingReady          Events = "recording.ready"
	EventsRecordingStarted        Events = "recording.started"
	EventsRecordingWaiting        Events = "recording.waiting"
	EventsMultistreamConnected    Events = "multistream.connected"
	EventsMultistreamError        Events = "multistream.error"
	EventsMultistreamDisconnected Events = "multistream.disconnected"
	EventsPlaybackUserNew         Events = "playback.user.new"
	EventsPlaybackAccessControl   Events = "playback.accessControl"
	EventsAssetCreated            Events = "asset.created"
	EventsAssetUpdated            Events = "asset.updated"
	EventsAssetFailed             Events = "asset.failed"
	EventsAssetReady              Events = "asset.ready"
	EventsAssetDeleted            Events = "asset.deleted"
	EventsTaskSpawned             Events = "task.spawned"
	EventsTaskUpdated             Events = "task.updated"
	EventsTaskCompleted           Events = "task.completed"
	EventsTaskFailed              Events = "task.failed"
)

func (e Events) ToPointer() *Events {
	return &e
}
func (e *Events) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stream.started":
		fallthrough
	case "stream.detection":
		fallthrough
	case "stream.idle":
		fallthrough
	case "recording.ready":
		fallthrough
	case "recording.started":
		fallthrough
	case "recording.waiting":
		fallthrough
	case "multistream.connected":
		fallthrough
	case "multistream.error":
		fallthrough
	case "multistream.disconnected":
		fallthrough
	case "playback.user.new":
		fallthrough
	case "playback.accessControl":
		fallthrough
	case "asset.created":
		fallthrough
	case "asset.updated":
		fallthrough
	case "asset.failed":
		fallthrough
	case "asset.ready":
		fallthrough
	case "asset.deleted":
		fallthrough
	case "task.spawned":
		fallthrough
	case "task.updated":
		fallthrough
	case "task.completed":
		fallthrough
	case "task.failed":
		*e = Events(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Events: %v", v)
	}
}

// LastFailure - failure timestamp and error message with status code
type LastFailure struct {
	// Timestamp (in milliseconds) at which the webhook last failed
	Timestamp *float64 `json:"timestamp,omitempty"`
	// Webhook failure error message
	Error *string `json:"error,omitempty"`
	// Webhook failure response
	Response *string `json:"response,omitempty"`
	// Webhook failure status code
	StatusCode *float64 `json:"statusCode,omitempty"`
}

func (l *LastFailure) GetTimestamp() *float64 {
	if l == nil {
		return nil
	}
	return l.Timestamp
}

func (l *LastFailure) GetError() *string {
	if l == nil {
		return nil
	}
	return l.Error
}

func (l *LastFailure) GetResponse() *string {
	if l == nil {
		return nil
	}
	return l.Response
}

func (l *LastFailure) GetStatusCode() *float64 {
	if l == nil {
		return nil
	}
	return l.StatusCode
}

// Status - status of webhook
type Status struct {
	// failure timestamp and error message with status code
	LastFailure *LastFailure `json:"lastFailure,omitempty"`
	// Timestamp (in milliseconds) at which the webhook last was
	// triggered
	//
	LastTriggeredAt *float64 `json:"lastTriggeredAt,omitempty"`
}

func (s *Status) GetLastFailure() *LastFailure {
	if s == nil {
		return nil
	}
	return s.LastFailure
}

func (s *Status) GetLastTriggeredAt() *float64 {
	if s == nil {
		return nil
	}
	return s.LastTriggeredAt
}

type Webhook struct {
	ID   *string `json:"id,omitempty"`
	Name string  `json:"name"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Kind *string `json:"kind,omitempty"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	UserID *string `json:"userId,omitempty"`
	// The ID of the project
	ProjectID *string `json:"projectId,omitempty"`
	// Timestamp (in milliseconds) at which stream object was created
	CreatedAt *float64 `json:"createdAt,omitempty"`
	Events    []Events `json:"events,omitempty"`
	URL       string   `json:"url"`
	// streamId of the stream on which the webhook is applied
	StreamID *string `json:"streamId,omitempty"`
	// status of webhook
	Status *Status `json:"status,omitempty"`
}

func (w *Webhook) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *Webhook) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *Webhook) GetKind() *string {
	if w == nil {
		return nil
	}
	return w.Kind
}

func (w *Webhook) GetUserID() *string {
	if w == nil {
		return nil
	}
	return w.UserID
}

func (w *Webhook) GetProjectID() *string {
	if w == nil {
		return nil
	}
	return w.ProjectID
}

func (w *Webhook) GetCreatedAt() *float64 {
	if w == nil {
		return nil
	}
	return w.CreatedAt
}

func (w *Webhook) GetEvents() []Events {
	if w == nil {
		return nil
	}
	return w.Events
}

func (w *Webhook) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *Webhook) GetStreamID() *string {
	if w == nil {
		return nil
	}
	return w.StreamID
}

func (w *Webhook) GetStatus() *Status {
	if w == nil {
		return nil
	}
	return w.Status
}

type WebhookInput struct {
	Name string `json:"name"`
	// The ID of the project
	ProjectID *string  `json:"projectId,omitempty"`
	Events    []Events `json:"events,omitempty"`
	URL       string   `json:"url"`
	// shared secret used to sign the webhook payload
	SharedSecret *string `json:"sharedSecret,omitempty"`
	// streamId of the stream on which the webhook is applied
	StreamID *string `json:"streamId,omitempty"`
}

func (w *WebhookInput) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *WebhookInput) GetProjectID() *string {
	if w == nil {
		return nil
	}
	return w.ProjectID
}

func (w *WebhookInput) GetEvents() []Events {
	if w == nil {
		return nil
	}
	return w.Events
}

func (w *WebhookInput) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}

func (w *WebhookInput) GetSharedSecret() *string {
	if w == nil {
		return nil
	}
	return w.SharedSecret
}

func (w *WebhookInput) GetStreamID() *string {
	if w == nil {
		return nil
	}
	return w.StreamID
}
