workflowVersion: 1.0.0
sources:
    openapi:
        inputs:
            - location: /Users/rafalleszko/repos/studio/packages/api/src/schema/api-schema.yaml
targets:
    first-target:
        target: go
        source: openapi
