workflowVersion: 1.0.0
sources:
    livepeer-studio-api:
        inputs:
            - location: https://raw.githubusercontent.com/livepeer/studio/sk/schema-fixes/packages/api/src/schema/api-schema.yaml
targets:
    my-first-target:
        target: go
        source: livepeer-studio-api
